### ISSUE TITLE
Whitespace is not allowed in build path.

### ISSUE THREAD

**Issue by ashutoshsharmagit** [mongodb/mongo-php-driver#1026]
Ashu:mongo-php-driver xxxxx yyyyy$ phpize
Invalid build path '/Users/xxxxx yyyyy/mongo-php-driver'. Whitespace is not allowed in build path.

how to fix this issue on MacBook pro aprt from changing user.

**Comment by alcaeus** [comment]
Building from a path with no spaces looks like the easiest way to fix this.

If you can't change the build path, I'd like to refer you to the [PHP issue tracker](https://bugs.php.net). The `phpize` script is provided by your installation of PHP, so any issues with that script will have to be fixed in PHP itself. As mentioned above, changing the build path is most likely easier than getting this fixed upstream.

I'm closing this issue here since it's not related to the driver itself.
