### ISSUE TITLE
Does not build in IBM i PASE environment

### ISSUE THREAD

**Issue by jwoehr** [mongodb/mongo-php-driver#1168]
### Bug Report
In the IBM i PASE (it's based on IBM AIX) environment with PHP + extensions installed from `http://repos.zend.com/ibmiphp` and further extensions installed from `http://repo.qseco.fr`, the command `pecl install mongodb` downloads but the build fails as shown in the attached document.
[pecl_mongodb_fail.txt](https://github.com/mongodb/mongo-php-driver/files/5403692/pecl_mongodb_fail.txt)

### Environment
IBM i 7.4 PASE
```
$ uname -a
OS400 OPENSRC 4 7 00210002307W Os
```

**Comment by ThePrez** [comment]
At a glance, it looks like you might need to build with compiler define `COMPAT_43` to build with the BSD 4.3-like functions that this seems to be using

**Comment by ThePrez** [comment]
I think the proper way to do this would be like so:
```fortran
phpize
CFLAGS=-DCOMPAT_43 CPPFLAGS=-DCOMPAT_43 ./configure
make
```

**Comment by jwoehr** [comment]
Trying to build from github src
```
export OBJECT_MODE=64
export COMPAT_43=1
phpize > /dev/null && \
./configure --enable-mongodb-developer-flags > /dev/null && \
make clean > /dev/null && make all > /dev/null && make install
```
So far got this warning:
`configure: WARNING: *** Please add powerpc-ibm-os400 to configure.ac checks!`

**Comment by jwoehr** [comment]
Oops, @ThePrez slipped in. Starting again with script:
```
export OBJECT_MODE=64
cd mongo-php-driver
git submodule update --init
phpize > /dev/null && \
CFLAGS=-DCOMPAT_43 CPPFLAGS=-DCOMPAT_43 ./configure --enable-mongodb-developer-flags > /dev/null && \
make clean > /dev/null && make all > /dev/null && make install
```

**Comment by jwoehr** [comment]
```$ ./build_driver.sh 
Submodule 'src/libmongoc' (https://github.com/mongodb/mongo-c-driver.git) registered for path 'src/libmongoc'
Submodule 'src/libmongocrypt' (https://github.com/mongodb/libmongocrypt.git) registered for path 'src/libmongocrypt'
Cloning into '/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc'...
Cloning into '/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongocrypt'...
Submodule path 'src/libmongoc': checked out '60267532b6feddad7ab93097d8917fa1dd7195df'
Submodule path 'src/libmongocrypt': checked out '052f7fc610f0cea83a2adf3dd263a5ff04833371'
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
configure: WARNING: *** Please add powerpc-ibm-os400 to configure.ac checks!
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libbson/src/bson/bson-oid.c:35:23: warning: 'gHexCharPairs' defined but not used [-Wunused-const-variable=]
 static const uint16_t gHexCharPairs[] = {
                       ^~~~~~~~~~~~~
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.c: In function 'mongoc_socket_accept_ex':
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.c:731:15: error: 'struct sockaddr_storage' has no member named 'ss_family'; did you mean '__ss_family'?
       if (addr.ss_family == AF_INET) {
               ^
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.c: In function '_mongoc_socket_try_sendv':
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.c:1295:10: warning: implicit declaration of function 'sendmsg' [-Wimplicit-function-declaration]
    ret = sendmsg (sock->sd,
          ^~~~~~~
make: *** [Makefile:491: src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.lo] Error 1
```

**Comment by ThePrez** [comment]
Oops.... my analysis had it backwards. Mongoc doesn't use the 4.3-style, but the headers are compiled with `COMPAT_43`, hence the mismatch. 
`-UCOMPAT_43` _might_ do something nice, but not betting on it...

**Comment by ThePrez** [comment]
I wonder if `COMPAT_43` is set somewhere as a side effect of `_BSD_SOURCE` being set (or some such silliness) though I can't track down where such a thing may be happening. 

As a desperate straw-grasping exercise, one might suggest adding an `os400` leg to CheckHost.m4. I could envision it looking like
```fortran
    *-*-linux*)
        os_linux=yes
        os_gnu=yes
        TARGET_OS=unix
        ;;
```

**Comment by ThePrez** [comment]
Even better, just build libmongoc standalone and then build the php driver to use the system libmongoc (I believe this can be done via ` --with-libmongoc` on the configure command)

**Comment by ThePrez** [comment]
Sorry for the multiple updates. 
Checking our libmongoc builds, we set `-D_BSD=44 -pthread` in CFLAGS

So I think your path to success is:
```fortran
export OBJECT_MODE=64
phpize > /dev/null && \
CFLAGS="-D_BSD=44 -pthread" CPPFLAGS="-D_BSD=44 -pthread" LDFLAGS="-Wl,-bbigtoc -pthread" ./configure --enable-mongodb-developer-flags > /dev/null && \
make clean > /dev/null && make all > /dev/null && make install
```

**Comment by jwoehr** [comment]
```
$ cat ../build_driver.sh 
BREP=..build_report_` date '+%Y%m%dT%H:%M:%S'`.txt
export OBJECT_MODE=64
phpize >${BREP}&& \
CFLAGS="-D_BSD=44 -pthread" CPPFLAGS="-D_BSD=44 -pthread" LDFLAGS="-Wl,-bbigtoc -pthread" ./configure --enable-mongodb-developer-flags >>${BREP}&& \
make clean >>${BREP}&& make all >>${BREP}&& make install >>${BREP}
```
Same error.
```
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.c: In function 'mongoc_socket_accept_ex':
/home/JWOEHR/work/PHP/mongo-php-driver/src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.c:731:15: error: 'struct sockaddr_storage' has no member named '__ss_family'; did you mean 'ss_family'?
       if (addr.ss_family == AF_INET) {
               ^
make: *** [Makefile:491: src/libmongoc/src/libmongoc/src/mongoc/mongoc-socket.lo] Error 1
```

**Comment by alcaeus** [comment]
This error is due to the detection of the `ss_family` member to `sockaddr_storage` not producing the expected result. Looking at [FindDependencies.m4](https://github.com/mongodb/mongo-php-driver/blob/8e4cefa44e41f82978c2e695680ef05ae826840e/scripts/autotools/libmongoc/FindDependencies.m4#L28), we check for its existence using `AC_CHECK_MEMBER` and set `MONGOC_HAVE_SS_FAMILY` accordingly. Despite the confusing naming, this is set if `sockaddr_storage` has `__ss_family` instead of `ss_family` (see [comment in mongoc-config.h.in](https://github.com/mongodb/mongo-c-driver/blob/282f110565239a0d5d91f1e5e2f91ba4bee57dc7/src/libmongoc/src/mongoc/mongoc-config.h.in#L386). The check was added as counterpart to the check in libmongoc itself as seen in [its build scripts](https://github.com/mongodb/mongo-c-driver/blob/282f110565239a0d5d91f1e5e2f91ba4bee57dc7/src/libmongoc/CMakeLists.txt#L443).

I'm not sure what exactly is going wrong here, so I apologise for any guesswork while trying to resolve this. Here are some things you can try:
* Check `config.log` and `src/libmongoc/src/libmongoc/src/mongoc/mongoc-config.h` for the result of this check. The error message suggests that this value is `0`, meaning that our check is wrong (since it obviously should be `1` due to the absence of `sockaddr_storage.ss_family`).
* Try compiling libmongoc by itself. I'll refer you to the [build instructions in the libmongoc docs](http://mongoc.org/libmongoc/current/installing.html#build-environment). If that build succeeds, that points to an error in our feature detection, while a failing build suggests a more general error in libmongoc.

As for the suggestion to compile libmongoc manually and using `--with-libmongoc`, please note that we deprecated this flag in favour of `--with-system-libs`. The reasoning here is that we always required you to specify both `--with-libmongoc` and `--with-libbson`, so having two separate flags for this didn't make sense, especially when we added libmongocrypt as an optional build dependency. The switch still works, just be aware that you'll have to provide system libmongoc and libbson for a build without bundled libraries to work.

Also, pinging @kevinAlbs as he was involved in the original fix and may be able to provide more insight as to what's going on here. Thanks for bearing with me while trying to figure out what's going on here!

**Comment by jwoehr** [comment]
@alcaeus Andreas, thanks for the tips. We will work on this and get back to you.

**Comment by NattyNarwhal** [comment]
I think the PHP driver side check is wrong.

In `mongo-socket.h`:

```
#if defined(_AIX) && !defined(MONGOC_HAVE_SS_FAMILY)
# define ss_family __ss_family
#endif
```

But in, `FindDependencies.m4`, the definitions seem reversed according to [`AC_CHECK_MEMBER`](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Generic-Structures.html):

```
# Check for sched_getcpu
AC_CHECK_FUNC([sched_getcpu],
              [AC_SUBST(MONGOC_HAVE_SCHED_GETCPU, 1)],
              [AC_SUBST(MONGOC_HAVE_SCHED_GETCPU, 0)])

AC_CHECK_TYPE([socklen_t],
              [AC_SUBST(MONGOC_HAVE_SOCKLEN, 1)],
              [AC_SUBST(MONGOC_HAVE_SOCKLEN, 0)],
              [#include <sys/socket.h>])

AC_CHECK_MEMBER([struct sockaddr_storage.ss_family],
                [AC_SUBST(MONGOC_HAVE_SS_FAMILY, 0)],
                [AC_SUBST(MONGOC_HAVE_SS_FAMILY, 1)],
                [#include <sys/socket.h>])
```

So the definition is set to 0, so then `mongo-config.h` will undefine `MONGOC_HAVE_SS_FAMILY`.

When I reverse the 0/1 in the `ss_family` check, it builds without any compatibility flags or other changes. I think the autotools/cmake checks from normal Mongo libraries should work like this too, but the PHP module doesn't use their build scripts even with the vendored copy.

**Comment by alcaeus** [comment]
@NattyNarwhal thank you for confirming this. When I first took a look I was convinced it was wrong, then convinced myself otherwise after reading the code some more. 🤦‍♂️

I've created #1169 to fix this, and we're also tracking this internally as PHPC-1703. We'll have this released in the upcoming driver patch release (currently scheduled for the first Tuesday in November).

**Comment by jwoehr** [comment]
@NattyNarwhal got this working and I am able to connect from IBM i PASE to Atlas. Thanks, @alcaeus
