### ISSUE TITLE
Key restrictions

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [mongodb/mongo-php-driver#1170]
From version 3.6 mongo supports key with `.` and `$`:
https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

It's not recommended to use those characters, but what do you think about this problem?
Now I have a project where I have to migrate data to MongoDB and some field has `.` inside the key name.

The test file where I can see the behavior is:

https://github.com/mongodb/mongo-php-driver/blob/master/tests/bulk/bulkwrite-update_error-001.phpt

I would like to know your opinion. 

Thanks.

**Comment by alcaeus** [comment]
Hi,

the problem with these field names is that they (currently) cannot be expressed in the query language, which is why the drivers don't support them. This is explained in the documentation:
> The MongoDB Query Language cannot always meaningfully express queries over documents whose field names contain these characters (see SERVER-30575).
>
> Until support is added in the query language, the use of $ and . in field names is not recommended and is not supported by the official MongoDB drivers.

There are some plans to change this, but since this requires server changes as well as driver changes, I can't comment on a specific timeline. Thanks for understanding!
