### ISSUE TITLE
Unable to load dynamic library 'mongodb' for PHP 8.0.0

### ISSUE THREAD

**Issue by pavinthan** [mongodb/mongo-php-driver#1181]
PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb' (tried: C:\php\ext\mongodb (The specified module could not be found), C:\php
\ext\php_mongodb.dll (The specified module could not be found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'mongodb' (tried: C:\php\ext\mongodb (The specified module could not be found), C:\php\ext\
php_mongodb.dll (The specified module could not be found)) in Unknown on line 0
PHP 8.0.0 (cli) (built: Nov 24 2020 22:02:58) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies

![image](https://user-images.githubusercontent.com/13897936/100396871-ea462980-306c-11eb-8de3-4e72500402e6.png)

**Comment by alcaeus** [comment]
Hi @pavinthan,

where did you obtain the DLL file? Did you compile it yourself or did you download it from the PECL repository? I'm asking because the [DLL list on PECL](https://pecl.php.net/package/mongodb/1.9.0/windows) does not list any PHP 8 builds (yet), so if you downloaded it from there I wouldn't expect this to work.

Looking at other packages on the download server (e.g. for [xdebug](https://windows.php.net/downloads/pecl/releases/xdebug/3.0.0/)), I can't see any PHP 8 DLLs despite their compatibility with PHP 8, so I assume that this is somewhat expected due to the builds no longer being provided by Microsoft itself ([source](https://externals.io/message/110907)). I'll try to figure out where/when Windows builds will be made available and report back once I know more.

**Comment by pavinthan** [comment]
@alcaeus Yes I used PHP 7.4 builds from https://windows.php.net/downloads/pecl/releases/mongodb/1.9.0/php_mongodb-1.9.0-7.4-nts-vc15-x64.zip

> I'll try to figure out where/when Windows builds will be made available and report back once I know more.
Thank you so much

**Comment by alcaeus** [comment]
> Yes I used PHP 7.4 builds

In general, you always need to select the correct DLL for your PHP version, otherwise it won't be loaded. Apart from not being compiled for PHP 8, the extension is also compiled using VC 15, whereas your PHP version was compiled with VC 19. Once PHP 8 builds are available, make sure to select the correct DLL.

I'm closing this issue as this isn't an issue with the extension itself but rather with the Windows build system PHP uses. I'll post an update once I know more about when and where PHP 8 builds will be available.

**Comment by alcaeus** [comment]
I asked about this in the PHP internals chat on StackOverflow. @cmb69 provided the following answer:
> the mass rebuilt usually only happens a few weeks after first GA release; the DLLs will be made available as usual (pecl.php.net and windows.php.net are community machines). A snapshot build of mongodb 1.9.0 is available at windows.php.net/downloads/pecl/snaps/mongodb/1.9.0.
