### ISSUE TITLE
Unable to load dynamic library 'mongodb.so': `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by flyneko** [mongodb/mongo-php-driver#1188]
Ubuntu 18.04
PHP 7.3.10 

Got following error
> Warning: PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /opt/lampp/lib/php/extensions/no-debug-non-zts-20180731/mongodb.so (/opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.60)), /opt/lampp/lib/php/extensions/no-debug-non-zts-20180731/mongodb.so.so (/opt/lampp/lib/php/extensions/no-debug-non-zts-20180731/mongodb.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Tried install older versions, install via pecl and manual compile. Results are the same.

**Comment by jmikola** [comment]
This appears to be an issue with your platform as opposed to a driver issue. Searching for the "CXXABI_1.3.8" error message turned up several discussions on the subject. Please read through the following Stack Overflow threads for potential solutions:

 * https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found
 * https://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by

An [answer](https://stackoverflow.com/a/23494975/162228) in the second thread explains that this may be caused by an incompatibility between your compiler and libstdc++ system library. The first thread is more active and has a few answers that may help you resolve this.
