### ISSUE TITLE
[HELP] Trouble installing on Mac ARM (M1)

### ISSUE THREAD

**Issue by pesseyjulien** [mongodb/mongo-php-driver#1194]
Hi,

Sorry it's not so much a bug but more a support request.

I'm having trouble installing the driver on my new mac (arm M1 chipset), getting the following error :

```
[27-Jan-2021 12:52:11 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /Applications/MAMP/bin/php/php7.4.12/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (dlopen(/Applications/MAMP/bin/php/php7.4.12/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so, 9): no suitable image found.  Did find:
	/Applications/MAMP/bin/php/php7.4.12/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so: mach-o, but wrong architecture
	/Applications/MAMP/bin/php/php7.4.12/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so: mach-o, but wrong architecture), /Applications/MAMP/bin/php/php7.4.12/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so (dlopen(/Applications/MAMP/bin/php/php7.4.12/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so, 9): image not found)) in Unknown on line 0
```
I have tried to build from source with following instructions :

```
/Applications/MAMP/bin/php/php7.4.12/bin/phpize
./configure --with-php-config="/Applications/MAMP/bin/php/php7.4.12/bin/php-config" CFLAGS="-arch arm64"
```

Any idea what is wrong ?

Thanks in advance for your help,
Julien

**Comment by jmikola** [comment]
@pesseyjulien: I'm not sure what has changed since you previously reported success in compiling the extension in https://github.com/mongodb/mongo-php-library/issues/799#issuecomment-757640313, but I think you'll have better luck by taking this question to MAMP forums, Stack Overflow, etc. To reiterate from the previous reply: we do build/test the driver for ARM in our CI environment, but we do not test on M1 specifically (although I don't think that's the issue here) nor do we test with third-party PHP bundles like MAMP, XAMPP, etc.

In [Setting Up an M1 Mac for Laravel Development with Homebrew, PHP, MySQL, Valet and Redis](https://austencam.com/posts/setting-up-an-m1-mac-for-laravel-development-with-homebrew-php-mysql-valet-and-redis), the author talks about Homebrew not yet having ARM builds of PHP. In that case, the user was compiling for an `x86_64` architecture. It's quite possible that MAMP's own PHP binaries are not compiled for ARM, in which case you'll need to compile the driver (which is dynamically loaded) with whatever architecture MAMP has (perhaps `x86_64`).

Gentle reminder for next time: please take any support questions directly to the [MongoDB Community Forums](https://developer.mongodb.com/community/forums/c/drivers-odms/7).

**Comment by pesseyjulien** [comment]
Yeah I actually never successed in installing/compiling the extension on my new mac.

I'm trying with pecl, from binary sources, nothing works..

I'm pretty sure the issue is related to MAMP but it's wrecking my head and I kinda wanted to see if anyone had a similar issue so It could help me.

It was a desperate call for help :) 

Thanks anyway and sorry for the trouble,
Julien
