### ISSUE TITLE
keys cannot contain "."

### ISSUE THREAD

**Issue by AChelnokov** [mongodb/mongo-php-driver#1195]
Starting with MongoDB 3.6, the server allows storing field names containing periods (i.e.) and dollar signs (i.e. $). 
https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

But the extension returns an exception if there is a period in the field names. 
`Fatal error: Uncaught MongoDB\Driver\Exception\InvalidArgumentException: invalid document for insert: keys cannot contain ".": "asd.asd"`
Perhaps this is due to key validation (since 1.6 version)

**Comment by jmikola** [comment]
> Perhaps this is due to key validation (since 1.6 version)

IIRC, the key validation was introduced in `ext-mongodb` version 1.3.0 by [PHPC-712](https://jira.mongodb.org/browse/PHPC-712).

All MongoDB drivers are currently blocked on the server implementing an escaping mechanism for special characters in queries (see: [SERVER-30575](https://jira.mongodb.org/browse/SERVER-30575)). Without that in place, there is effectively no way to query for this data, since the server would always interpret `foo.bar` as a field path instead of a single field name with a dot. Please see my previous replies in for more context:

 * https://github.com/mongodb/mongo-php-driver/issues/844#issuecomment-392651174
 * https://github.com/mongodb/mongo-php-driver/issues/790#issuecomment-377934512

If you absolutely want to get around the driver's validation, I presume you could manually execute [insert](https://docs.mongodb.com/manual/reference/command/insert/) and [update](https://docs.mongodb.com/manual/reference/command/update/) commands (via `executeWriteCommand()`); however, that's venturing outside of the driver and library API for [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) operations so features like retryable writes would no longer apply (in addition to any difficulties you may have trying to query for the data).
