### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by Eric-chy** [mongodb/mongo-php-driver#1215]
php-fpm：
    pm.max_children = 1024
    pm.start_servers = 32
    pm.min_spare_servers = 32
    pm.max_spare_servers = 1024

Number of servers： 2

The maximum number of mongodb connections is 8000,Our request volume is very small, but the number of connections is full every once in a while, and the number of connections is full after a while after restarting.How can I release the connection?

**Comment by alcaeus** [comment]
The documentation on php.net contains a [chapter dedicated to connection persistence](https://www.php.net/manual/en/mongodb.connection-handling.php). For all following examples, let's assume that each PHP process repeatedly runs a `ping` command on the cluster it's connected to. Assuming you always use the same arguments when constructing your manager, each PHP process will reuse a single libmongoc client during its lifetime. Once a command is run, one or more connections are opened depending on topology.

In your config, you start out with 32 processes on 2 servers, meaning 64 connections to a standalone server. As requests pour in, FPM will start additional PHP processes to handle requests, up to a maximum of 1024 per server, which means you now have 2048 open connections to a standalone server. It's important to note that the driver always connects to all servers in the topology. That that our number of 2048 connections needs to be multiplied with the number of servers in the cluster. For standalone topologies, this is always one; for replica sets it's the number of servers in the set, and for sharded clusters it's the number of `mongos` instances indicated in the connection string. Note that if you use Seedlist Discovery (indicated by the `mongodb+srv://` protocol in the connection string), the driver connects to all mongos instances discovered through the DNS lookup, but my memory is a little flakey on that.

That means that if you're running a replica set with 4 members, your "small" setup will already be past the 8k connection limit (4 x 2048 connections). I don't know what kind of topology you are connecting to, but you can see that the numbers start running away from you quite quickly.

Since you mention "our request volume is very small", I want to go deeper into your FPM config. The `max_children` and `start_servers` are fine, but I'm a little concerned about the `max_spare_servers` value. Essentially, you're instructing FPM to not end any spare servers at all. So, if you get a short spike in traffic to warrant a large number of additional PHP processes, these won't be shut down once the spike has passed. This keeps a number of connections open even if they are not needed. To further elaborate on this math, let's assume that our request occupies a single PHP process for approximately 100 ms. This means that with the setup above, you can handle around 20k requests per second before requests will have to wait for an available FPM process (in my math, I assumed lossless scaling, so the numbers may be a little lower than that). It's not unheard of, but it's not what I'd call "very small request volume". My suggestion is to adjust the `max_spare_servers` number to ensure that stale processes are ended, freeing up connections.
