### ISSUE TITLE
Connection and topology persistence : Parallel(multithreading) support

### ISSUE THREAD

**Issue by ziaratban** [mongodb/mongo-php-driver#1224]
Hi
According to [this issue ](https://github.com/mongodb/mongo-php-library/issues/756), the `mongodb php driver` create a connection for each thread and i can finally  disable this feature with the `disableClientPersistence` param.

But i have a large threads, `open & close` is not good solution. good solution is persistence feature.

Is there no solution to this problem?

**For example**
```php
$manager = new MongoDB\Driver\Manager(...);
$sharedKey = $manager->GetSharedKey();
$i = 1000;
while($i--){
    \parallel\run(function()use($sharedKey){
        $manager = new MongoDB\Driver\Manager(...,[],['sharedKey' => $sharedKey]);
    });
}
```

**Comment by jmikola** [comment]
> good solution is persistence feature.

I don't understand what you mean by this, as that is the driver's original behavior. Rather than saying that the driver "create(s) a connection for each thread", it will be helpful to acknowledge the documented behavior from [Connection Handling](https://www.php.net/manual/en/mongodb.connection-handling.php) in the PHP.net docs.

The driver's original behavior is to persist `mongoc_client_t` objects based on a hash of constructor arguments for `MongoDB\Driver\Manager` instances. The driver will ignore unrecognized options in the connection string or either option arrays (`$uriOptions` and `$driverOptions`); however, they will still factor into the hash created from the constructor arguments. To that end, passing an extra option like `sharedKey` can be used to ensure a previously persisted `mongoc_client_t` is _not_ re-used, provided the value of `sharedKey` is unique. Depending on whether or not `disableClientPersistence` is used, those `mongoc_client_t` objects would then persist until the corresponding Manager goes out of scope or the process ends.

A `mongoc_client_t` (and thus a Manager) can _never_ be used concurrently by different threads without risking IO errors (e.g. reading server replies out of order). That is not something that we can address in the driver itself, as it's inherent to the design of libmongoc.

A multi-threaded (or forking) PHP application has two choices in this regard:

 * Have each thread construct its own Manager with a unique `mongoc_client_t`, either via unique constructor arguments or using `disableClientPersistence` (after it becomes available in ext-mongodb 1.10)
 * Implement your own class that pools Manager instances and allows threads to check out and return Managers on their own. This would be similar to what [libmongoc itself provides](http://mongoc.org/libmongoc/current/tutorial.html#threading); however, in libmongoc all pooled clients share the same topology monitor. This would not be the case in PHP, since every Manager and `mongoc_client_t` would be independent.

There are no plans to provide a direct PHP API for libmongoc's client pool, as that would be a considerable effort (both for initial design and ongoing maintenance) and it's also unclear how that might complicate integration with the library package.

**Comment by ziaratban** [comment]
Thanks @jmikola _(As always powerful)_.

This is my perception according to this doc [(Connection handling and persistence)](https://www.php.net/manual/en/mongodb.connection-handling.php) :

![image](https://user-images.githubusercontent.com/6462878/120757122-5f674f80-c525-11eb-8480-f7dcd063fa52.png)

`persistence` is a good behavior. but why this behavior is not implemented in multi-threading?

> A mongoc_client_t (and thus a Manager) can never be used concurrently by different threads without risking IO errors (e.g. reading server replies out of order). That is not something that we can address in the driver itself, as it's inherent to the design of libmongoc.

![image](https://user-images.githubusercontent.com/6462878/120758029-95f19a00-c526-11eb-93ac-4e67522c13a3.png)

Finally the persistence topology can work in parallelism (multiprocessing) but cannot working in concurrency(multithreading).

Is this correct?

**Comment by jmikola** [comment]
> ![image](https://user-images.githubusercontent.com/6462878/120757122-5f674f80-c525-11eb-8480-f7dcd063fa52.png)

That diagram is not accurate, as it shows several processes (parent and children) sharing the same Manager. With respect to the PHP extension, memory is _never_ shared between different processes. I'll come back to this in a bit.

In your diagram, Manager also seems synonymous with libmongoc's client object (i.e. `mongoc_client_t`); however, that fails to acknowledge that multiple Managers _may_ share the same `mongoc_client_t` if their constructor arguments are the same (i.e. yielding the same hash used to persist `mongoc_client_t` objects).

Just to explain the relationship between Managers and `mongoc_client_t` objects, it'd be helpful to read through the [`phongo_manager_init`](https://github.com/mongodb/mongo-php-driver/blob/1.10.0alpha1/php_phongo.c#L3393) function in the extension. This is called after we create the Manager zval (during its constructor). After creating a hash from the constructor arguments (`php_phongo_manager_make_client_hash`), we check whether a `mongoc_client_t` already exists for that hash in an internal HashTable by calling `php_phongo_find_persistent_client`. If a client isn't found, we'll create a new one and persist it.

Driver version 1.10.0 will change this slightly by checking for `disableClientPersistence`. If that is set, we will skip the check for an existing `mongoc_client_t` _and_ avoid persisting the new `mongoc_client_t` we create. That is to say, we'll construct a new libmongoc client _just_ for that Manager instance, and allow it to be destroyed when the Manager ultimately goes out of scope.

Coming back to the "_never_ shared" statement: when a process forks, the entire memory footprint is copied for the child process(es). This includes all PHP zvals, the internaal HashTable, and all of libmongoc's data structures. The only thing that _may_ end up shared at this point is the network sockets themselves, which is why we have the following note on the [`Manager::_construct()`](https://www.php.net/manual/en/mongodb-driver-manager.construct.php_) and [(Connection handling and persistence)](https://www.php.net/manual/en/mongodb.connection-handling.php) pages:

> On Unix platforms, the MongoDB driver is sensitive to scripts that use the fork() system call without also calling exec(). Users are advised not to re-use MongoDB\Driver\Manager instances in a forked child process.

We most recently attempted to address this in [PHPC-1274](https://jira.mongodb.org/browse/PHPC-1274) by detecting when a process forks and attempting to close any sockets that were created by a parent process; however, the solution cannot cover all edge cases.

The risk of two processes sharing the same network socket is the same as multiple threads sharing them. MongoDB's wire protocol currently does not support [pipelining](https://en.wikipedia.org/wiki/Protocol_pipelining) and expects messages to be sent and received in order. Consider the following exchange:

 1. Thread 1 sends command `foo` on socket 1
 2. Thread 2 sends command `bar` on socket 1
 3. Thread 2 reads `bar` response from socket 1. This yields an error, as the response from `foo` must be read first

> ![image](https://user-images.githubusercontent.com/6462878/120758029-95f19a00-c526-11eb-93ac-4e67522c13a3.png)

The diagram also makes the same mistake as the first in not distinguishing between Managers and `mongoc_client_t` objects. If each threads constructs its own Manager, those Manager boxes should exist within the individual threads. That HashTable (mapping of Managers to `mongoc_client_t` objects) can exist outside of threads, since that's something the PHP extension handles for the entire process (irrespective of threading).

Since all threads share the same memory, they have access to the same persistent HashTable. Assuming `disableClientPersistence` is not being used, if two threads were to construct a Manager with the same arguments those Managers would end up using the same `mongoc_client_t` object. This invites the same out-of-order problem as the forking example where network sockets end up being shared; however, it's actually a bit worse as now the entire libmongoc object may be accessed concurrently. While libmongoc does use mutexes around critical points (e.g. internal [server monitoring](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst)), `mongoc_client_t` objects are still not intended to be shared by multiple threads.

For that reason, a multi-threaded application desiring persistence would need to implement its own pool of Manager objects (each created with `disableClientPersistence` to ensure no `mongoc_client_t` objects are inadvertently shared amongst Managers).

**Comment by ziaratban** [comment]
Thanks @jmikola for the full explanation .

> The driver's default persistence logic was designed with PHP's traditional worker process model in mind (e.g. FPM) to allow monitoring state and connections to be re-used by subsequent requests handled by a process. I don't think it's relevant for a multi-threaded application, since those typically have an architecture more similar to a CLI app.

With the advent of `php 8` in this world, we need to move more towards CLI.

**Comment by jmikola** [comment]
> we need to move more towards CLI.

Just to connect this with my previous comment that a CLI app has little need of persistence since it is inherently one request. Even if the CLI app is behaving as an app server itself, it is a single request according to [PHP's lifecycle](https://www.phpinternalsbook.com/php7/extensions_design/php_lifecycle.html) (e.g. RINIT/RSHUTDOWN occur once).
