### ISSUE TITLE
How to use session created from MongoDBClient

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-driver#1309]
Hello. When creating a session using \MongoDB\Client() (a different repository, I understand, but stick with me here), I don't understand how to use that session in \MongoDB\Driver\Manager because of the following error:

```
[MongoDB\Driver\Exception\InvalidArgumentException]  
  Cannot use Session started from a different Manager 
```

The use case here is using a session created in Client to use in executeCommand():

```
$client = new \MongoDB\Client(
    'mongodb://localhost'
);
$session = $client->startSession();
// now want to run executeCommand()
$manager = new \MongoDB\Driver\Manager(
    'mongodb://localhost'
);
$command = new \MongoDB\Driver\Command(['ping' => 1]);
$manager->executeCommand('admin', $command, ['session' => $session]);
// error!
```

What am I missing here? Is there an better (easier) way to do this? To be clear, this is a simplified example. The $client is running some operations using the session, so that's why it is instantiated.
Thanks.

**Comment by jmikola** [comment]
I assume the identical connection strings in your example code actually differ in practice. The logic that leads to this error message is a bit more permissive, as the extension only raises that error if the underlying libmongoc client objects differ (see: [`phongo_parse_session()`](https://github.com/mongodb/mongo-php-driver/blob/1.12.1/php_phongo.c#L641)).

Per [Connection handling and persistence](https://www.php.net/manual/en/mongodb.connection-handling.php) in the extension docs, multiple Managers constructed with the same constructor options (including the connection string) should share the same libmongoc client. [`MongoDB\Client::__construct()`](https://github.com/mongodb/mongo-php-library/blob/1.11.0/src/Client.php#L130) essentially delegates to the Manager constructor (much like [`Client::startSession()`](https://github.com/mongodb/mongo-php-library/blob/1.11.0/src/Client.php#L353)), so if we took your example code literally I would not expect to see this error.

The justification for this restriction is that client sessions are tracked by an internal pool in libmongoc, so they are not intended to be used by different clients.

You have a couple of options here:

 * Rather than construct a new Manager from scratch, call [`MongoDB\Client::getManager()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBClient-getManager/) to obtain the Client's internal Manager. Then, you are guaranteed that both objects use the same libmongoc client and can use the same session.
 * If you only need to run a `ping` command, you can select a Database object from the original Client and use [`MongoDB\Database::command()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBDatabase-command/). That would also be more concise as you wouldn't need to deal with `MongoDB\Driver\Command` at all.

**Comment by 719media** [comment]
Thanks for the explanation. For your information, when I literally use this code in a test script:

```
$client = new \MongoDB\Client(
    'mongodb://localhost'
);
$session = $client->startSession();
// now want to run executeCommand()
$manager = new \MongoDB\Driver\Manager(
    'mongodb://localhost'
);
$command = new \MongoDB\Driver\Command(['ping' => 1]);
$manager->executeCommand('admin', $command, ['session' => $session]);
```

Results in
```
  [MongoDB\Driver\Exception\InvalidArgumentException]  
  Cannot use Session started from a different Manager  
```


However, the following
```
$client = new \MongoDB\Client(
    'mongodb://localhost'
);
$session = $client->startSession();
$db = $client->selectDatabase('test');
$db->command(['ping' => 1], ['session' => $session]);
```

works fine

**Comment by 719media** [comment]
Also by way of information, the following
```
$client = new \MongoDB\Client(
    'mongodb://localhost'
);
$session = $client->startSession();
$client2 = new \MongoDB\Client(
    'mongodb://localhost'
);
$db = $client2->selectDatabase('test');
$db->command(['ping' => 1], ['session' => $session]);
```
does work as you described, so something about creating a new manager with the same connection string doesn't quite work the same way. My guess is that the Client class has a default typeMap:

```
private static $defaultTypeMap = [
    'array' => BSONArray::class,
    'document' => BSONDocument::class,
    'root' => BSONDocument::class,
];
```

which makes it "different" than the Manager class. Anyway, assuming that's the case, this can be closed as it isn't a bug, just a clarification that using Manager directly with the "same" connection string won't work, because the MongoDB\Client class does infer some differences causing the connection string to not match up. Thanks for the help.

**Comment by jmikola** [comment]
> My guess is that the Client class has a default typeMap

The `typeMap` option for the Client is actually [unset before we construct the Manager](https://github.com/mongodb/mongo-php-library/blob/1.11.0/src/Client.php#L128). Looking into this a bit more, I realize it's actually due to the library setting the [`driver` key in `$driverOptions`](https://github.com/mongodb/mongo-php-library/blob/1.11.0/src/Client.php#L123) in order to provide more info for the [connection handshake](https://github.com/mongodb/specifications/blob/master/source/mongodb-handshake/handshake.rst#connection-handshake). @alcaeus actually implemented this several years ago in https://github.com/mongodb/mongo-php-library/commit/c31f5d5d8cef9f41d3e9dab0f220600063612fb5 for [PHPLIB-516](https://jira.mongodb.org/browse/PHPLIB-516), which is why I didn't remember it offhand.

I'll revise my previous comment to account for this.

> Anyway, assuming that's the case, this can be closed as it isn't a bug

I concur there doesn't seem to be any bug here. Thanks for following up so we could determine the actual cause!
