### ISSUE TITLE
BSON field 'count.query' is the wrong type 'array', expected type 'object' during command "count"

### ISSUE THREAD

**Issue by tweber68** [mongodb/mongo-php-driver#1313]
### Bug Report

The following code

```php
<?php
$mongoManager = new \MongoDB\Driver\Manager('mongodb://localhost/dsp_qatest');
$cmd = [
    'count' => "bids",
    'query' => [],
];

$cmd = (object) $cmd;

$dbCommand = new \MongoDB\Driver\Command($cmd);

$res = $mongoManager->executeCommand('dsp_qatest', $dbCommand);

var_dump(iterator_to_array($res));
```

throws the exception: 

```
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\CommandException: BSON field 'count.query' is the wrong type 'array', expected type 'object' in /home/theo/test.php:13
```

As well if I remove the typecast `(object)`.

### Environment

OS Ubuntu 18.04
MongoDB 4.2 and 4.4
PHP 7.4 (I think also with PHP 8.1)
php-mongodb-extension version: 1.11.0

```
php -i | grep -E 'mongodb|libmongoc|libbson'
/etc/php/7.4/cli/conf.d/20-mongodb.ini,
mongodb
libbson bundled version => 1.19.1
libmongoc bundled version => 1.19.1
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc ICU => disabled
libmongoc compression => enabled
libmongoc compression snappy => enabled
libmongoc compression zlib => enabled
libmongoc compression zstd => enabled
libmongocrypt bundled version => 1.2.1
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
mongodb.mock_service_id => Off => Off
```

### Test Script

run from CLI

### Expected and Actual Behavior

No exception expected. The db and the collection exists.

**Comment by jmikola** [comment]
Per [Persisting Data: Serialization to BSON](https://www.php.net/manual/en/mongodb.persistence.serialization.php) in the extension documentation, a "packed array" (i.e. empty array, or an array with keys sequential numeric keys starting at 0) converts to a BSON array (i.e. type `0x04` in the [BSON spec](https://bsonspec.org/spec.html)). Other PHP arrays will convert to a BSON object (i.e. type `0x03`).

The [count](https://www.mongodb.com/docs/manual/reference/command/count/) command expects the `query` option to be a document (i.e. BSON object), which agrees with the server error message you observed.

There should never be any reason to cast the first parameter of [`MongoDB\Driver\Command::__construct()`](https://www.php.net/manual/en/mongodb-driver-command.construct.php) to an object. Per the documentation, an array or object are both accepted for that parameter and the [internal code](https://github.com/mongodb/mongo-php-driver/blob/1.13.0/src/MongoDB/Command.c#L117) will always ensure it serializes as a BSON document. This is related to another point in [Persisting Data: Serialization to BSON](https://www.php.net/manual/en/mongodb.persistence.serialization.php):

> A top-level (root) document, always serializes as a BSON document. 

Rather than cast `$cmd` to an object, you should consider casting the `query` field to an object. This is what we do in the[`MongoDB\Operation\Count::createCommandDocument()`](https://github.com/mongodb/mongo-php-library/blob/1.12.0/src/Operation/Count.php#L187), which is the underlying code path for [`MongoDB\Collection::count()`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-count/).

Alternatively:

 * Use the PHP library and [`MongoDB\Collection::count()`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-count/) instead of the extension.
 * Omit the `query` option, since that would be equivalent to an empty document.

**Comment by tweber68** [comment]
@jmikola Thank you for the explication! I think we know now how to cope.
