### ISSUE TITLE
Segment Fault presists with repeated find

### ISSUE THREAD

**Issue by gdccyuen** [mongodb/mongo-php-driver#1314]
I am new to mongodb, but was tasked to test the performance. Here is the script:
<?php
require 'vendor/autoload.php';
$connStr = "mongodb://127.0.0.1";
$mongoClient = new MongoDB\Client($connStr);
$configDB = $mongoClient->test;
for($i=0; $i<100000; $i++) {
   $config = $configDB->config->find([], ['sort'=>["_id"=>-1]])->toArray()[0];
}
print($config['timestamp']."\n");
?>

Run for about 10 seconds then:
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/test/vendor/mongodb/mongodb/src/Model/BSONArray.php on line 87

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/test/vendor/mongodb/mongodb/src/Model/BSONArray.php on line 87
Segmentation fault

Even more problematic is after that I cannot run anything about find() in mongo-php-driver, the segment fault persist, even after I reboot the VM!

**Comment by jmikola** [comment]
In the future, please do not be so quick to disregard the [bug report template](https://raw.githubusercontent.com/mongodb/mongo-php-driver/master/.github/ISSUE_TEMPLATE/bug-report.md). We intentionally set that up to collect important information on bug reports and minimize the back and forth required to diagnose an issue.

Please share the following:

 * What operating system and PHP version are you using? Mention if PHP was installed through a third-party bundle (e.g. MAMP, XAMPP) and report its version if applicable.
 * What version of MongoDB are you using? Include details about the topology (e.g. replica set, sharded cluster) and how you are connecting to the database (e.g. TLS connections, authentication). If possible, share your connection string and additional URI options (be sure to redact any auth credentials). Please specify whether you are self-hosting the database or using a cloud provider, such as MongoDB Atlas.
* Include version information for the extension, libmongoc, and libbson. This may be collected by grepping phpinfo() output: `php -i | grep -E 'mongodb|libmongoc|libbson'`
* Include version information for the library. This may be collected by running the following from your project's root directory: `composer show mongodb/mongodb`

Additionally, please share:

 * Please share a reproducible PHP script. Specifically, I'd like to see how you are creating the `MongoDB\Client` object.
 * Share details about what type of documents are stored in the collection being queried. If the documents are roughly similar, it'd be helpful to share a single document and tell us approximately how many other documents are contained in the collection. This is relevant because you're querying for _all_ documents in the collection (descending by `_id`).
 * If you are able to [provide a backtrace](https://bugs.php.net/bugs-generating-backtrace.php) of the segfault, that would be most helpful. Doing so will require that you have debug symbols available for PHP and the extension.

> Even more problematic is after that I cannot run anything about find() in mongo-php-driver, the segment fault persist, even after I reboot the VM!

I don't understand what this means.

If you are asking why the out-of-memory (OOM) error occurs, I would think that is fairly reproducible if your PHP memory limit and the database contents remain the same across VM restarts.

If you are asking about why you cannot find documentation for a `find()` method in the extension, it is because the extension has no such API. The `find()` method is implemented in the library package and is documented in [`MongoDB\Collection::find()`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-find/). The extension, upon which the library is built, has a lower-level API and the corresponding method used by `Collection::find()` would be [`MongoDB\Driver\Server::executeQuery()`](https://www.php.net/manual/en/mongodb-driver-server.executequery.php) (related to [`MongoDB\Driver\Manager::executeQuery()`](https://www.php.net/manual/en/mongodb-driver-manager.executequery.php)).
