### ISSUE TITLE
Can't load monogodb php driver on Mac with M1 chip

### ISSUE THREAD

**Issue by salehasadi** [mongodb/mongo-php-driver#1330]
### Bug Report
Hi, I'm trying to use mongodb inside php script, I followed up the instructions provided by MongoDb official website.
now mongodb.so file exist in extensions path of my php inside of XAMPP but as I include it in php.ini it throws this error to me and also does not load in list of modules and phpinfo.
as I did same way on another laptop which is running ubuntu and that works as expected, I don't have any idea why this is happening on my mac device.
I tried to install using Pecl, manual build but both resulted in same situation at last.
could you please help me about this? thanks.

> PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (dlopen(/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so, 0x0009): symbol not found in flat namespace '_ZSTD_compress'), /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so (dlopen(/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so, 0x0009): tried: '/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so' (no such file))) in Unknown on line 0

![image](https://user-images.githubusercontent.com/14921568/173026194-adab4c79-106e-41b9-88b9-809faee1e545.png)
![image](https://user-images.githubusercontent.com/14921568/173026275-d93c6e35-8209-4a2b-ba65-1867438b35c7.png)
![image](https://user-images.githubusercontent.com/14921568/173026540-2174d0af-7e1b-413a-88ec-3160972eb6de.png)

### Environment
macOs Montrey 12.4
Chip Apple M1 Pro
MongoDB v5.0.7
mongodb driver 1.13.0 (installed using pecl)
XAMPP
PHP 7.4.27 (cli) (built: Dec 21 2021 05:12:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by jmikola** [comment]
This may be the result of the PHP extension and existing zstd shared library on your system having been compiled differently or having inconsistent architectures. See https://stackoverflow.com/a/39519008/162228 for some previous discussion on this that explains more detail about the error. I came across many other threads (some related to M1 specifically, although I don't believe the error itself is unique to that platform) by searching for the generic message ["symbol not found in flat namespace"](https://www.google.com/search?q=%22symbol+not+found+in+flat+namespace%22).

zstd is one of several compression libraries that the driver checks for automatically during compilation (see: [`CheckCompression.m4`](https://github.com/mongodb/mongo-php-driver/blob/1.13.0/scripts/autotools/libmongoc/CheckCompression.m4#L53)). We don't currently have any `configure` options to control detection of compression libraries, so I can only think of two possible solutions:

 * Sort out the incompatibility in your zstd system library
 * Build libmongoc as a system library w/o zstd, and then compile the PHP driver against libmongoc

I can't assist with zstd directly, but I do have some guidance on building libmongoc. Following the [libmongoc install docs](http://mongoc.org/libmongoc/current/installing.html), you can explicitly disable zstd compression with `-DENABLE_ZSTD=OFF`
(see: [`CMakeLists.txt`](https://github.com/mongodb/mongo-c-driver/blob/1.21.2/CMakeLists.txt#L32) and [Configuring the build](http://mongoc.org/libmongoc/current/installing.html#configuring-the-build)). Then, the PHP driver would need to be compiled to prefer the libmongoc system library instead of its bundled submodules via the `--with-mongodb-system-libs=yes` `configure` option (see: [`config.m4`](https://github.com/mongodb/mongo-php-driver/blob/1.13.0/config.m4#L193)), which is briefly discussed in [Building the MongoDB PHP Driver from source](https://www.php.net/manual/en/mongodb.installation.manual.php#mongodb.installation.manual).

**Comment by salehasadi** [comment]
@jmikola I tried to build using libmongoc now error message changed to that this is not compatible.

> Warning: PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (dlopen(/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so, 0x0009): tried: '/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))), /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so (dlopen(/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so, 0x0009): tried: '/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so' (no such file))) in Unknown on line 0

**Comment by jmikola** [comment]
@salehasadi: This is definitely outside the scope of the PHP driver. It looks like your machine is compiling the extension (and libmongoc) for the arm64 architecture, but you're attempting to load them in XAMPP, which uses x86_64.

A related discussion is https://github.com/krakjoe/apcu/issues/419, although in that case the user had the inverse issue: they were attempting to compile an extension for arm64.

[M1 Mac — How to switch the Terminal between x86_64 and arm64](https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9) may provide some assistance. That is just something I came across from a cursory web search on your error message and looking up discussions about compiling for specific architectures.

Unless something specific to the PHP driver comes up, I will not be able to provide further assistance here as I do not develop with macOS (nor do I have access to an M1 machine).

**Comment by salehasadi** [comment]
> @salehasadi: This is definitely outside the scope of the PHP driver. It looks like your machine is compiling the extension (and libmongoc) for the arm64 architecture, but you're attempting to load them in XAMPP, which uses x86_64.
> 
> A related discussion is [krakjoe/apcu#419](https://github.com/krakjoe/apcu/issues/419), although in that case the user had the inverse issue: they were attempting to compile an extension for arm64. [M1 Mac — How to switch the Terminal between x86_64 and arm64](https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9) may provide some assistance. That is just something I came across from a cursory web search on your error message and looking up discussions about compiling for specific architectures.
> 
> Unless something specific to the PHP driver comes up, I will not be able to provide further assistance here as I do not develop with macOS (nor do I have access to an M1 machine).

Hi @jmikola,
I tried to build the driver as x86_64 because as you mentioned PHP of XAMPP is using that architecture.

> /Applications/XAMPP/xamppfiles/bin/php: Mach-O 64-bit executable x86_64

also I tried changing by switching terminal to x86_64 and run Terminal using Rosetta.

but all had same result. I don't know if I'm checking a part in a wrong way or not.

also I tried to install using this command but I don't know how I can force PECL to don't use zstd.

> arch -x86_64 sudo pecl install mongodb
