### ISSUE TITLE
No suitable servers found: `serverSelectionTimeoutMS` expired: [socket timeout calling hello on '[myserver]:27017']

### ISSUE THREAD

**Issue by Hippolyte-wia** [mongodb/mongo-php-driver#1363]
### Bug Report

I am migrating my mongo databases from my local server to a managed MongoDB on DigitalOcean.
Everything worked fine on my server, but since I migrated all my dbs to the managed mongo server, nothing works anymore.
I always have the same error in my PHP script :

```
Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found: `serverSelectionTimeoutMS` expired: [socket timeout calling hello on '[myserver]:27017'] in [myserverpath]/finder2.php:41

Stack trace:
#0 [myserverpath]/finder2.php(41): MongoDB\Driver\Manager->executeCommand('db', Object(MongoDB\Driver\Command))
#1 {main} thrown in [myserverpath]/finder2.php on line 41
```

The only thing I changed is the connection string.
For information, I can connect to the new server with Mongo shell on the same server as the PHP script.

### Environment

**PHP Version :** 7.4.30

**Extension informations :** 
libbson bundled version => 1.20.0
libmongoc bundled version => 1.20.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongoc compression zstd => disabled
libmongocrypt bundled version => 1.3.0
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
mongodb.mock_service_id => Off => Off

**MongoDB :** 
Version : MongoDB 5
I don't really know the configuration since it's DigitalOcean who manage everything.
I have the fully managed version with the first configuration and no other options.
The config : 1 GB RAM / 1vCPU / 15 GB Disk / Primary only / AMS3 - MongoDB 5

### Test Script

```php
$client = new MongoDB\Driver\Manager(
	'mongodb+srv://[user]:[password]@[doserver]/admin',
	[
		"serverSelectionTryOnce" => false,
		"serverSelectionTimeoutMS" => 5000,
		"tls" => true,
		"ssl" => true,
		"replicaSet" => "db-mongodb-ams3-19362"
	]
);
$command = new MongoDB\Driver\Command(['ping' => 1]);
$client->executeCommand('db', $command);

var_dump($client->getServers());
```

I tried multiple value for "serverSelectionTimeoutMS" but nothing changes...

### Expected and Actual Behavior

**Expected Behavior :** 
The PHP script connects to the DigitalOcean database.

**Actual Behavior :** 
Every time I try to make a request to the new server, it fails with the same error.

Any help on this would be appreciated !

**Comment by jmikola** [comment]
> I tried multiple value for "serverSelectionTimeoutMS" but nothing changes...

Some feedback on your URI:

 * `ssl` is a deprecated alias of `tls`, so you need not specify both
 * `serverSelectionTryOnce=false` should not generally be necessary since the extension supports retryable reads and writes by default. Leaving this disabled should allow the driver to fail sooner, which may be preferable in an application where you might want to yield an error to the client ASAP w/o blocking the PHP worker.
 
   That said, if you _do_ want to disable `tryOnce` behavior (i.e. rely on a server selection loop) _and_ you're connecting to a replica set, you may want to ensure that `serverSelectionTimeoutMS` is at least as long as the expected time for a failover election to complete. [Replica Set Elections](https://www.mongodb.com/docs/manual/core/replica-set-elections/) _conservatively_ suggests 12 seconds, but five seconds is likely too short.
 
   This advice isn't relevant for sharded clusters, since `mongos` insulates the driver from directly dealing with replica set elections. For a sharded cluster connection, you can get by with a much lower `serverSelectionTimeoutMS`. 

> For information, I can connect to the new server with Mongo shell on the same server as the PHP script.

If this is the case, it's likely that your PHP environment (or some related firewall configuration) is not allowing outgoing connections. This is commonly caused by SELinux if you'd like to research that further.

If you'd like to test an outgoing connection without using the PHP driver, you can experiment with a [Connection Tester](https://github.com/jmikola/buildfest2021/tree/master/connect) script I developed last year. Two shortcomings with the current version of that tool:

 * It does not yet support SRV URIs, so you'll need to get a non-SRV URI for the cluster (assuming DigitalOcean provides that)
 * It does not yet detect the `tls` URI option, so you'll need to ensure `ssl` is included in the connection string

Assuming you can get a non-SRV URI, the README should be enough to get you started. In summary, the script takes a MongoDB connection string and issues an `isMaster` command (older equivalent of `hello`) using raw PHP socket functions instead of the `mongodb` extension. If that also fails to establish a connection to the server it's very likely that you're dealing with a PHP environment issue and nothing to do with the driver itself.

Even if you can't get a non-SRV URI from DigitalOcean, you may be able to create one using the host in the exception message (e.g. "myserver"), since that's coming from a connection attempt in the driver _after_ SRV records have been resolved for [initial DNS seedlist discovery](https://github.com/mongodb/specifications/blob/master/source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst). For example:

```
mongodb://<user>:<password>@<server>:27017/admin?ssl=true&replicaSet=db-mongodb-ams3-19362
```

That should be a viable URL to feed into the `connect.php` script.

**Comment by Hippolyte-wia** [comment]
Thanks for your fast response !

> It does not yet support SRV URIs, so you'll need to get a non-SRV URI for the cluster (assuming DigitalOcean provides that)

Unfortunately DigitalOcean does not provide a non-SRV URI and I tried to connect without it (with Mongo Compass) but it doesn't seem to work.

I used your script with the URI exemple you provided and got this error : 

```
Found 1 host(s) in the URI. Will attempt to connect to each. Could not connect to <server>:27017: php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by Hippolyte-wia** [comment]
I found out that the port wasn't open on our host's firewall. Everything works fine now!

Thank you for your help!
