### ISSUE TITLE
Compilation error under cygwin

### ISSUE THREAD

**Issue by matyhtf** [mongodb/mongo-php-driver#1381]
### Bug Report

Compilation error under cygwin

### Environment

* php 8.1.12
* ext-mongodb 1.14.2
* cygwin [3.3.6](https://cygwin.com/pipermail/cygwin-announce/2022-September/010707.html)
* uname -a  `CYGWIN_NT-10.0-19042 pc-08 3.3.6-341.x86_64 2022-09-05 11:15 UTC x86_64 Cygwin`

#### Cygwin Packages

```
wget tar libtool bison gcc-g++ autoconf automake openssl libpcre2-devel libssl-devel libcurl-devel libxml2-devel libxslt-devel libgmp-devel ImageMagick libpng-devel libjpeg-devel libfreetype-devel libwebp-devel libsqlite3-devel zlib-devel libbz2-devel libzip-devel libicu-devel libonig-devel libcares-devel libsodium-devel libyaml-devel libMagick-devel 
```

### Test Script

```shell
git clone https://github.com/php/php-src.git
cd php-src
git checkout PHP-8.1.12
cd ext
pecl download mongodb-1.14.2
tar xvf mongodb-1.14.2.tgz
mv mongodb-1.14.2 mongodb
cd ..
```

#### Configure

```shell
./buildconf --force
./configure --prefix=/usr --disable-all \
    --disable-fiber-asm \
    --disable-opcache \
    --without-pcre-jit \
    --with-openssl --enable-openssl \
    --with-curl \
    --with-iconv \
    --enable-intl \
    --with-bz2 \
    --enable-bcmath \
    --enable-filter \
    --enable-session \
    --enable-tokenizer \
    --enable-mbstring \
    --enable-ctype \
    --with-zlib \
    --with-zip \
    --enable-posix \
    --enable-sockets \
    --enable-pdo \
    --with-sqlite3 \
    --enable-phar \
    --enable-pcntl \
    --enable-mysqlnd \
    --with-mysqli \
    --enable-fileinfo \
    --with-pdo_mysql \
    --with-pdo-sqlite \
    --enable-soap \
    --with-xsl \
    --with-gmp \
    --enable-exif \
    --with-sodium \
    --enable-xml --enable-simplexml --enable-xmlreader --enable-xmlwriter --enable-dom --with-libxml \
    --enable-gd --with-jpeg  --with-freetype \
    --enable-mongodb
```

#### Build
```shell
make -j 8

/cygdrive/d/workspace/php-src/ext/mongodb/src/libmongocrypt/kms-message/src/kms_crypto.h:45:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   45 | kms_crypto_init ();
      | ^~~~~~~~~~~~~~~
/cygdrive/d/workspace/php-src/ext/mongodb/src/libmongocrypt/kms-message/src/kms_crypto.h:48:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   48 | kms_crypto_cleanup ();
      | ^~~~~~~~~~~~~~~~~~
/cygdrive/d/workspace/php-src/ext/mongodb/src/libmongocrypt/src/os_posix/os_dll.c:130:2: error: #error "Don't know how to do mcr_dll_path() on this platform"
  130 | #error "Don't know how to do mcr_dll_path() on this platform"
      |  ^~~~~

```

### Expected and Actual Behavior

successfully compiled

**Comment by matyhtf** [comment]
Thanks. After specifying the `--with-mongodb-client-side-encryption=no` argument, it can be successfully compiled, but a new error occurs when linking.

```shell
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: warning: --export-dynamic is not supported for PE+ targets, did you mean --export-all-symbols?
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: ext/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-client.o: in function `_mongoc_get_rr_search':
/cygdrive/d/workspace/php-src/ext/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-client.c:499: undefined reference to `__ns_initparse'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/d/workspace/php-src/ext/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-client.c:511: undefined reference to `__ns_parserr'
collect2: error: ld returned 1 exit status
make: *** [Makefile:291: bin/php] Error 1
```

**Comment by jmikola** [comment]
That last error matches what was originally reported in https://github.com/mongodb/mongo-php-driver/issues/848 (older issue from 2018). Based on https://bugs.bitlbee.org/ticket/1098, it looks like these APIs aren't available under Cygwin at all. I expect the fix for this issue would require a similar patch for libmongoc; however, libmongoc does not support or test on Cygwin (it's only mentioned in passing in the [install docs](http://mongoc.org/libmongoc/current/installing.html)). The closest environment in their [CI matrix](https://evergreen.mongodb.com/waterfall/mongo-c-driver) appears to be MinGW.

As for the PHP driver, our Windows builds are only tested with the [standard PHP SDK](https://github.com/php/php-sdk-binary-tools), which uses Visual Studio and the `config.w32` build script (not Autotools). Since neither our build scripts nor libmongoc support Cygwin, I'm not confident that fixing the above issue would fully resolve this. There are likely other incompatibilities lurking that would need to be resolved as well -- something to keep in mind if you want to venture down the rabbit hole and contribute patches.

Is there any reason you can't use Visual Studio and the PHP SDK to compile the driver and/or just use a DLL? I realize those were unavailable for the past few months after PECL stopped building them, but we recently started attaching DLLs for various Windows environments to our GitHub releases as a work around.

**Comment by matyhtf** [comment]
@jmikola 
Thanks, we use pcntl, posix and other extensions that only support the linux/unix platform, and cygwin is required to run in the windows OS.  Hope to support the cygwin platform in the future.

Best regards.
