### ISSUE TITLE
How to use pecl command to enable the option "--enable-mongodb-crypto-system-profile" ?

### ISSUE THREAD

**Issue by vndroid** [mongodb/mongo-php-driver#1420]
### Bug Report

This option can be used in manual mode, example:

```bash
docker container run --rm -it php:8.2.5-fpm-alpine /bin/sh
```

In the container, run:

```sh
apk upgrade --no-cache
apk add --no-cache autoconf build-base
apk add --no-cache icu-dev zstd-dev snappy-dev openssl-dev cyrus-sasl-dev
wget https://pecl.php.net/get/mongodb-1.15.2.tgz
tar xf mongodb-1.15.2.tgz
cd mongodb-1.15.2/
phpize
./configure --with-mongodb-ssl=openssl --enable-mongodb-crypto-system-profile --with-mongodb-icu=yes --with-mongodb
-sasl=cyrus
make
make install
docker-php-ext-enable mongodb
php -i | grep mongo
```

output:

```
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
mongodb
libmongoc bundled version => 1.23.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => enabled
libmongoc SASL => enabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => enabled
libmongoc compression zlib => enabled
libmongoc compression zstd => enabled
libmongocrypt bundled version => 1.5.2
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
PWD => /var/www/html/mongodb-1.15.2
$_SERVER['PWD'] => /var/www/html/mongodb-1.15.2
$_ENV['PWD'] => /var/www/html/mongodb-1.15.2
```

Everything is working fine.

### Environment

Docker Container
PHP 8.2.5 alpine

### Bug Reproduce

Use command pecl install can not use the option:

```bash
pecl install -D 'with-mongodb-ssl=openssl enable-mongodb-crypto-system-profile=yes with-mongodb-icu=yes with-mongodb-sasl=cyrus' mongodb
```

or

```bash
pecl install -D 'with-mongodb-ssl=openssl enable-mongodb-crypto-system-profile with-mongodb-icu=yes with-mongodb-sasl=cyrus' mongodb
```

None of them work properly.

In the container, run:

```sh
apk upgrade --no-cache
apk add --no-cache autoconf build-base
apk add --no-cache icu-dev zstd-dev snappy-dev openssl-dev cyrus-sasl-dev

docker-php-ext-enable mongodb
php -i | grep mongo
```

The blank line is the command above.

Output:

```
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
mongodb
libmongoc bundled version => 1.23.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => enabled
libmongoc compression zlib => enabled
libmongoc compression zstd => enabled
libmongocrypt bundled version => 1.5.2
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
```

How to deal with this problem?

**Comment by jmikola** [comment]
Quoting `pecl help install` output:

```
-D OPTION1=VALUE[ OPTION2=VALUE], --configureoptions=OPTION1=VALUE[ OPTION2=VALUE]
      space-delimited list of configure options
```

Supporting that `pecl` option requires the extension to add `<extsrcrelease>` to its `package.xml` and define a `<configureoption>` tag for each build flag it wishes to expose (see: [ext-swoole's `package.xml`](https://github.com/swoole/swoole-src/blob/v5.0.3/package.xml#L2411)).

[PHPC-1017](https://jira.mongodb.org/browse/PHPC-1017) is an existing ticket where we considered doing so; however, we ultimately didn't move forward because it would introduce interactive prompts to `pecl install mongodb`, which would be problematic for non-interactive installs (e.g. deployments, CI jobs). It may be something we can consider for 2.0 along with other breaking changes, but not before then. 

As discussed in [this Stack Overflow thread](https://stackoverflow.com/questions/8141407/install-pecl-modules-without-the-prompts), there are a number of ways to overcome the prompts (such as `--configureoptions`), but that all requires action on the user's part.

If you're set on using PECL, you could download the package (also attached to our GitHub releases) and manually patch the `package.xml` file. We could also theoretically do this by creating a separate `mongodb-configurable` package, although I don't think it'd be kosher to publish that through PECL (even if we used `<providesextension>` to alias it as `mongodb`). It would probably just end up as an additional attachment to GitHub releases. I'm not sure either of those would be more convenient than just compiling the driver from source.

**Comment by vndroid** [comment]
> Quoting `pecl help install` output:
> 
> ```
> -D OPTION1=VALUE[ OPTION2=VALUE], --configureoptions=OPTION1=VALUE[ OPTION2=VALUE]
>       space-delimited list of configure options
> ```
> 
> Supporting that `pecl` option requires the extension to add `<extsrcrelease>` to its `package.xml` and define a `<configureoption>` tag for each build flag it wishes to expose (see: [ext-swoole's `package.xml`](https://github.com/swoole/swoole-src/blob/v5.0.3/package.xml#L2411)).
> 
> [PHPC-1017](https://jira.mongodb.org/browse/PHPC-1017) is an existing ticket where we considered doing so; however, we ultimately didn't move forward because it would introduce interactive prompts to `pecl install mongodb`, which would be problematic for non-interactive installs (e.g. deployments, CI jobs). It may be something we can consider for 2.0 along with other breaking changes, but not before then.
> 
> As discussed in [this Stack Overflow thread](https://stackoverflow.com/questions/8141407/install-pecl-modules-without-the-prompts), there are a number of ways to overcome the prompts (such as `--configureoptions`), but that all requires action on the user's part.
> 
> If you're set on using PECL, you could download the package (also attached to our GitHub releases) and manually patch the `package.xml` file. We could also theoretically do this by creating a separate `mongodb-configurable` package, although I don't think it'd be kosher to publish that through PECL (even if we used `<providesextension>` to alias it as `mongodb`). It would probably just end up as an additional attachment to GitHub releases. I'm not sure either of those would be more convenient than just compiling the driver from source.

Since the automation solution for pecl is provided, I think it is necessary.

And since all other options already support configuration using the pecl method, then this parameter should be supported as well, unless this parameter is deprecated.

It is inelegant for the user to do the compilation manually and only for mongodb.

**Comment by jmikola** [comment]
> Sorry, I just checked the configuration and found that many of the parameters are set to auto by default, so installing the dependencies will compile automatically, not because the -D parameter is in effect.

I just tested this locally by building a PECL package for 1.16.0-dev with some `./configure` options exposed in `package.xml`:

```xml
<extsrcrelease>
 <configureoption default="auto" name="with-mongodb-client-side-encryption" prompt="client-side-encryption?"/>
 <configureoption default="auto" name="with-mongodb-ssl" prompt="ssl?"/>
</extsrcrelease>
```

The default values defined in our build scripts (e.g. `PHP_ARG_WITH([mongodb-ssl]...)` in [CheckSSL.m4](https://github.com/mongodb/mongo-php-driver/blob/1.15.3/scripts/autotools/libmongoc/CheckSSL.m4#L1-L6) are independent of the defaults specified in `package.xml`. In the absence of a `default` attribute for a `<configureoption/>` tag, PECL defaults to `null` (see: [PEAR/Builder.php](https://github.com/pear/pear-core/blob/v1.10.13/PEAR/Builder.php#L396)), which results in an empty string being passed to `./configure` (e.g. `--with-mongodb-ssl=`). That can lead to some unexpected behavior, which I've reported in [PHPC-2225](https://jira.mongodb.org/browse/PHPC-2225).

In any event, I'm not too concerned about missing `default` values in `package.xml`, as we'd be sure to define those and keep them consistent with the build scripts.

> It is inelegant for the user to do the compilation manually and only for mongodb.

I don't disagree, but my primary concern is that introducing `<configureoption/>` parameters in a _minor_ release of the extension will immediately break existing, non-interactive builds for the driver.

With the above modification to `package.xml` in place, an existing command to install the package is left hanging at a prompt:

```
$ pecl install -f mongodb-1.16.0.tgz 
818 source files, building
running: phpize
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829
client-side-encryption? :
```

I realize `-D` or `--configureoptions` can be used to overcome that, but that doesn't address existing, scripted installs in the wild. We'll have to give this some thought before moving forward. I've moved [PHPC-1017](https://jira.mongodb.org/browse/PHPC-1017) back to "Needs Triage" for the time being so the team can revisit it.

There might also be some improvements we can make to PECL itself that may help, such as detecting non-interactive environments, bypassing the UI prompt, and just using defaults from `<configureoption/>`.

**Comment by vndroid** [comment]
> With the above modification to `package.xml` in place, an existing command to install the package is left hanging at a prompt:
> 
> ```
> $ pecl install -f mongodb-1.16.0.tgz 
> 818 source files, building
> running: phpize
> Configuring for:
> PHP Api Version:         20220829
> Zend Module Api No:      20220829
> Zend Extension Api No:   420220829
> client-side-encryption? :
> ```
> 
> I realize `-D` or `--configureoptions` can be used to overcome that, but that doesn't address existing, scripted installs in the wild. We'll have to give this some thought before moving forward. I've moved [PHPC-1017](https://jira.mongodb.org/browse/PHPC-1017) back to "Needs Triage" for the time being so the team can revisit it.

As far as I remember, this is not something to worry about, when building in a container, it will automatically build using the default values and will not be left hanging.

By the way, can you give me the 1.16-dev patch? Are the changes made directly to the file [bin/package.xml.in](https://github.com/mongodb/mongo-php-driver/blob/master/bin/package.xml.in)?

```
<extsrcrelease>
 <configureoption default="auto" name="with-mongodb-client-side-encryption" prompt="client-side-encryption?"/>
 <configureoption default="auto" name="with-mongodb-ssl" prompt="ssl?"/>
</extsrcrelease>
```

**Comment by jmikola** [comment]
> By the way, can you give me the 1.16-dev patch? Are the changes made directly to the file [bin/package.xml.in](https://github.com/mongodb/mongo-php-driver/blob/master/bin/package.xml.in)?

Yes, see the diff below. Note that I didn't add all of the `configure` options -- only two to play around with how `pecl install --configureoptions` works (which lead to an [interesting discovery](https://twitter.com/jmikola/status/1656871678985768965)).

```diff
diff --git a/bin/package.xml.in b/bin/package.xml.in
index 631f54f3..939247b6 100644
--- a/bin/package.xml.in
+++ b/bin/package.xml.in
@@ -67,5 +67,8 @@ necessary to build a fully-functional MongoDB driver.
   </required>
  </dependencies>
  <providesextension>mongodb</providesextension>
- <extsrcrelease/>
+ <extsrcrelease>
+  <configureoption default="auto" name="with-mongodb-client-side-encryption" prompt="client-side-encryption?"/>
+  <configureoption default="auto" name="with-mongodb-ssl" prompt="ssl?"/>
+ </extsrcrelease>
 </package>
```

As for building your own package, you can take a look at ["Build PECL package" in CONTRIBUTING.md](https://github.com/mongodb/mongo-php-driver/blob/master/CONTRIBUTING.md#build-pecl-package) for more info. Steps are roughly as follows:

 * Check out a tag in the driver repository (e.g. 1.15.3) and update submodules
 * Replace `<extsrcrelease/>` in `bin/package.xml.in` as needed
 * Run `make package.xml` to generate `package.xml`
 * Add something within `<notes></notes>`, since it must be non-empty
 * Run `make package` to generate a tarball (e.g. `mongodb-1.15.3.tgz`).

Alternatively, you can grab an existing tarball (from PECL or our GitHub Releases) and modify `package.xml` directly. That might be more robust, since you coul script the process of extracting, patching, and rebuilding the archive.

> As far as I remember, this is not something to worry about, when building in a container, it will automatically build using the default values and will not be left hanging.

If you end up investigating this yourself, I'd be interested to hear back about this. I didn't see anything in the PECL installer that would bypass an interactive prompt during installation (for a package with one or more `<configureoption>` definitions).

**Comment by jmikola** [comment]
Configure options are exposed to PECL as of the [1.17.0] release.

**Comment by vndroid** [comment]
This is wonderful! Thanks a lot.
