### ISSUE TITLE
Random MongoDB\Driver\Exception\RuntimeException

### ISSUE THREAD

**Issue by magnusjt** [mongodb/mongo-php-driver#144]
I'm getting some seemingly random MongoDB\Driver\Exception\RuntimeException. For example:

````
PHP Fatal error:  Uncaught exception 'MongoDB\Driver\Exception\RuntimeException' in /vagrant/vendor/mongodb/mongodb/src/Operation/CreateIndexes.php:93
Stack trace:
#0 /vagrant/vendor/mongodb/mongodb/src/Operation/CreateIndexes.php(93): MongoDB\Driver\Server->executeCommand('test', Object(MongoDB\Driver\Command))
#1 /vagrant/vendor/mongodb/mongodb/src/Operation/CreateIndexes.php(72): MongoDB\Operation\CreateIndexes->executeCommand(Object(MongoDB\Driver\Server))
#2 /vagrant/vendor/mongodb/mongodb/src/Collection.php(194): MongoDB\Operation\CreateIndexes->execute(Object(MongoDB\Driver\Server))
#3 /vagrant/vendor/mongodb/mongodb/src/Collection.php(163): MongoDB\Collection->createIndexes(Array)
````

I've also gotten this exception when doing simple Find, BulkWrite, and others. It does not happen every time, seems random.

I'm not getting any message with the exception, so I don't really know what's wrong. Any tips?

**Comment by magnusjt** [comment]
Update: If I step through the code with xdebug enabled, I get this exception every time.

**Comment by bjori** [comment]
Its due to a bug in the code that checks if the socket is active.
The code gets executed every time a socket hasn't been used for over a second. It is meant to confirm the socket is still open.
The bug makes inverses the check, so it will always fail if the socket is valid after a second.

See https://github.com/mongodb/mongo-php-driver/issues/132
Not sure why that is marked as fixed as the patch hasn't been merged yet.

**Comment by magnusjt** [comment]
Ok, good to know it's a trivial bug. Thanks for the reply.

**Comment by jmikola** [comment]
#135 has been merged to master and [PHPC-487](https://jira.mongodb.org/browse/PHPC-487) has been resolved.
