### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by dawjan** [mongodb/mongo-php-driver#164]
Can't find it:

http://windows.php.net/downloads/pecl/releases/mongodb/1.0.1/

https://pecl.php.net/package/mongodb/1.0.1/windows

btw
Find any think on google about new php7 drivers for mongoDB its almost impossible due the miss matched names, lack of tutorials

I think phpredis has better community, support for PHP7

**Comment by jmikola** [comment]
What binaries are you looking for? https://pecl.php.net/package/mongodb/1.0.1/windows has builds for 5.5 and 5.6. Windows builds for 5.4 are not possible due to [PHPC-238](https://jira.mongodb.org/browse/PHPC-238), and we haven't prioritized that issue on account of 5.4 no longer being supported by PHP.net.

PHP 7 support is still being worked on. I expect to release 1.1.0 later today with MongoDB 3.2 support, after which https://github.com/mongodb/mongo-php-driver/pull/136 will need to be rebased and work can continue as we hunt down some outstanding memory leaks. That is being tracked in [PHPC-285](https://jira.mongodb.org/browse/PHPC-285).

**Comment by dawjan** [comment]
php7 definetly :)

I play some litted with php_mongodb: https://github.com/dawjan/php7-mongodb

But i found better way to support mongo extension for php7
https://github.com/mongofill/mongofill
-- this is liblary for HHVM but is working on php7 only need enable socks

**Comment by jmikola** [comment]
Closing this since https://github.com/mongodb/mongo-php-driver/pull/175 (PHP 7 support) has been merged to master. We should have a new release out in a day or two with those changes.
