### ISSUE TITLE
Documentation - Bulk update - only first matching document gets updated. Required "multi" flag missing.

### ISSUE THREAD

**Issue by andzandz** [mongodb/mongo-php-driver#229]
In the bulk documentation file/page:
https://github.com/mongodb/mongo-php-driver/blob/master/docs/bulk.md
http://mongodb.github.io/mongo-php-driver/bulk/

These example queries:

```
$bulk->update(
    ["_id" => $hayley_id],
    ['$set' => ["citizen" => "Iceland"]],
    ["limit" => 1, "upsert" => false]
);
$bulk->update(
    ["citizen" => "Iceland"],
    ['$set' => ["viking" => true]],
    ["limit" => 0, "upsert" => false]
);
$bulk->update(
    ["name" => "Chuck Norris"],
    ['$set' => ["viking" => false]],
    ["limit" => 1, "upsert" => true]
];
```

All of these will only update the first matching document. The "limit" => 0 in the second update() call clearly implies updating multiple documents (one for each Icelandic citizen)

The multi flag (required to be true to update multiple documents) defaults to false: http://php.net/manual/en/mongodb-driver-bulkwrite.update.php

This fixed query will update multiple documents:

```
$bulk->update(
    ["citizen" => "Iceland"],
    ['$set' => ["viking" => true]],
    ["limit" => 0, "upsert" => false, "multi" => true]
);
```

Please add the multi flag to the documentation. Thanks!

**Comment by jmikola** [comment]
@andzandz: Thanks for pointing this out. The `gh-pages` branch on this repository pre-dates http://php.net/mongodb, which now consolidates the common documentation for the PHP and HHVM extensions. We're actually going to remove the GitHub docs, so users are directed to the canonical manual on PHP.net (tracking with [PHPC-584](https://jira.mongodb.org/browse/PHPC-584)).

That said, GitHub-hosted docs will remain in place for the [userland library](https://github.com/mongodb/mongo-php-library/), since that isn't included on PHP.net.
