### ISSUE TITLE
Int64 / 32

### ISSUE THREAD

**Issue by ZorgUK** [mongodb/mongo-php-driver#240]
In the old MongoDB library you could create MongoInt32 and MongoInt64 objects, which converted to NumberLong() and NumberInt() in MongoDB as per:

https://docs.mongodb.org/manual/core/shell-types/

I see no replacement for these in MongoDB/BSON, is there any way to do it?

**Comment by derickr** [comment]
No, the driver picks the right type automatically depending on the size of the value:
https://github.com/mongodb/mongo-php-driver/blob/master/src/bson.c#L48
We decided that, as there are no differences in handling NumberInt vs. NumberLong in the database, this functionality was no longer needed. 

Do you have a specific use case where you need this?

**Comment by ZorgUK** [comment]
My documents are just built on a hard typed schema, I like to maintain this hard typing as best I can inside MongoDB as well so my ints go to NumberInts, my longs go to NumberLongs and my floats go in as is.

Eitherway they'll be recast on the way out anyway, so it's not a requirement, I just thought it was neater that way.

**Comment by jacqueswaller** [comment]
The one use case we've had is for when our client makes use of unsigned int32, which if we forced it to be a MongoInt32 would automatically convert to/from the signed int32 used by mongodb (with large numbers becoming negative but that was fine).

The main benefit of this is that we assumed the numbers were saved with 4 bytes in the database itself (instead of 8) which adds up in the long term.

**Comment by derickr** [comment]
The conversion was a side effect that you really can't rely on on multiple platforms.

As we now already pick the smallest type that fits, the size benefit does really no longer exist either.

I'm marking this "closed" as it works as it should.

**Comment by andydeng** [comment]
But there are other language using other driver had to specify int32 or int64 to query to get the right data. In my system, i change mongo driver to mongodb driver, php itself can set&get data, but since some fileds are mixed with int32 & int64, our java server can't query the data right. it's really not inconvenient with multi language to access same data.

**Comment by jmikola** [comment]
@andydeng: I'm not sure what you're referring to, but from the documentation on [BSON Types](https://docs.mongodb.org/manual/reference/bson-types/#comparison-sort-order):

> MongoDB treats some types as equivalent for comparison purposes. For instance, numeric types undergo conversion before comparison.

For example, if a field is storing the number 42 as a 32-bit integer and you specify query criteria to match the document with 42 as a 64-bit integer, the server will still match the document. Likewise for other comparisons, range queries, etc.

**Comment by tonyzheng121** [comment]
it's a bad design, we should decide which type we store data.
