### ISSUE TITLE
No php_mongodb.dll file in this archive ?

### ISSUE THREAD

**Issue by aymeric75** [mongodb/mongo-php-driver#251]
Hi, 

 As it's written on this website: http://www.hongkiat.com/blog/webdev-with-mongodb-part3/, i need to unzip mongo-php-driver archive to get php_mongo.dll, but i can't find it...

Any help ?

Cheers

**Comment by jacqueswaller** [comment]
The Windows binaries are at https://pecl.php.net/package/mongodb

**Comment by jacqueswaller** [comment]
Actually, as best as I can tell that tutorial is for the old driver available at https://pecl.php.net/package/mongo

**Comment by jmikola** [comment]
Thanks for answering, @jacqueswaller. I think we can close this out.

That blog post is definitely quite old, as it refers to version 1.2.12 of the legacy driver. GitHub has also deprecated repository downloads since then, so the https://github.com/mongodb/mongo-php-driver/downloads link is now empty. Additionally, we've renamed the repositories, so the legacy driver is now located at https://github.com/mongodb/mongo-php-driver-legacy/.

If you need Windows DLLs for the legacy driver, you'll also find those on PECL: https://pecl.php.net/package/mongo
