### ISSUE TITLE
undefined symbol: spl_ce_RuntimeException

### ISSUE THREAD

**Issue by byargv** [mongodb/mongo-php-driver#353]
```
[root@localhost mongodb-1.1.8]# php
Warning: PHP Startup: Unable to load dynamic library '/usr/pkgs/php/lib/php/extensions/no-debug-non-zts-20131226/mongodb.so' - /usr/pkgs/php/lib/php/extensions/no-debug-non-zts-20131226/mongodb.so: undefined symbol: spl_ce_RuntimeException in Unknown on line 0

PHP 5.6.23
phpmongodb 1.1.8

${prefix}php/bin/phpize
./configure CPPFLAGS="-I${prefix}openssl/include/ -I${prefix}zlib/include/ -I${prefix}pcre/include/" LDFLAGS="-L${prefix}openssl/lib/ -L${prefix}zlib/lib/ -L${prefix}pcre/lib/" \
	--with-php-config=${prefix}php/bin/php-config \
	--with-openssl-dir=${prefix}openssl/ \
	--with-pcre-dir=${prefix}pcre/ \
	--enable-mongodb
```

**Comment by jmikola** [comment]
Does your version of PHP report the SPL extension as available? AFAIK, it is always compiled into PHP since 5.3 and cannot be disabled.

Also, did you compile the extension against the very same version of PHP (and `phpize`) that you are using to load it and trigger the undefined symbol error? 

@derickr: We do not list SPL as a hard dependency, nor do we check the `HAVE_SPL` constant; however, [src/MongoDB/Exception/RuntimeException.c](https://github.com/mongodb/mongo-php-driver/blob/master/src/MongoDB/Exception/RuntimeException.c) includes `<ext/spl/spl_exceptions.h>`, which exports `spl_ce_RuntimeException`, which is what other PHP extensions relying on the SPL exceptions also do. The notable exclusion is PDO, which has some [code for a soft dependency](https://github.com/php/php-src/blob/php-5.6.23/ext/pdo/pdo.c#L74), but that may be a relic from when SPL was actually optional in PHP.

**Comment by derickr** [comment]
Some distributions put it in a separate extension. @byargv, which distribution and/or OS are you using? And how did you compile the extension?

**Comment by byargv** [comment]
function DREPLY()
{
	if [[ "$?" != "0" ]];then
		DREPLY="no";
		while [[ "${DREPLY}" != "yes" ]] 
		do
			echo "Error ----> ${1} ----> ${2}.  Continue ? [yes]:";
			read DREPLY;
		done
	fi
}

function php()
{
	DWGET php-5.6.23.tar.gz

	DWGET redis-2.2.8.tgz
	rm -Rf ${target}php-5.6.23/ext/redis
	mv ${target}redis-2.2.8 ${target}php-5.6.23/ext/redis

	DWGET memcached-2.2.0.tgz
	rm -Rf ${target}php-5.6.23/ext/memcached
	mv ${target}memcached-2.2.0 ${target}php-5.6.23/ext/memcached

	DWGET imagick-3.4.1.tgz
	rm -Rf ${target}php-5.6.23/ext/imagick
	mv ${target}imagick-3.4.1 ${target}php-5.6.23/ext/imagick
	
	export PKG_CONFIG_PATH=${prefix}ImageMagick/lib/pkgconfig/

	cd ${target}php-5.6.23
	rm -f ./configure
	./buildconf --force
	DREPLY php buildconf
	./configure --prefix=${prefix}php \
	--enable-mysqlnd \
	--with-mysqli=mysqlnd \
	--with-mysql=${prefix}mysql \
	--with-mysql-sock=/tmp/mysql.sock \
	--without-pdo-sqlite \
	--with-gd \
	--disable-short-tags \
	--with-png-dir=${prefix}libpng \
	--with-jpeg-dir=${prefix}jpeg \
	--with-freetype-dir=${prefix}freetype2 \
	--with-zlib-dir=${prefix}zlib \
	--with-curl=${prefix}curl \
	--with-openssl=${prefix}openssl \
	--with-openssl-dir=${prefix}openssl \
	--with-libxml-dir=${prefix}libxml2 \
	--with-bz2=${prefix}bzip2 \
	--with-mcrypt=${prefix}mcrypt \
	--with-mhash=${prefix}mhash \
	--enable-calendar \
	--enable-ftp \
	--enable-mbstring=all \
	--enable-bcmath \
	--enable-ctype \
	--enable-exif \
	--enable-gd-native-ttf \
	--enable-shmop \
	--enable-sockets \
	--enable-zip \
	--enable-soap \
	--enable-sigchild \
	--with-mcrypt=${prefix}libmcrypt \
	--enable-fpm \
	--with-fpm-user=vboxsf \
	--with-fpm-group=vboxsf \
	--enable-sysvmsg \
	--enable-sysvsem \
	--enable-sysvshm \
	--without-sqlite3 \
	--disable-pdo \
	--disable-phar \
	--enable-pcntl \
	--enable-memcached \
	--enable-memcached-json \
	--with-libmemcached-dir=${prefix}libmemcached/ \
	--with-imagick=${prefix}ImageMagick \
	--enable-redis \
	--without-pear
	DREPLY php configure
	make
	DREPLY php make
	make install
	DREPLY php install
	ln -sf ${prefix}php/bin/php /usr/local/bin/
}

function phpmongodb()
{
	#DWGET mongodb-1.1.8.tgz
	cd ${target}mongodb-1.1.8
	${prefix}php/bin/phpize
	./configure CPPFLAGS="-I${prefix}openssl/include/ -I${prefix}zlib/include/ -I${prefix}pcre/include/" LDFLAGS="-L${prefix}openssl/lib/ -L${prefix}zlib/lib/ -L${prefix}pcre/lib/" \
	--with-php-config=${prefix}php/bin/php-config \
	--with-openssl-dir=${prefix}openssl/ \
	--with-pcre-dir=${prefix}pcre/ \
	--enable-mongodb
	DREPLY phpmongodb configure
	make
	DREPLY phpmongodb make
	make install
	DREPLY phpmongodb install
}

**Comment by byargv** [comment]
try several times,i found it is affected by "redis-2.2.8.tgz"

**Comment by jmikola** [comment]
I expect this is due to the following in [redis.c](https://github.com/phpredis/phpredis/blob/363195b97368db1ae43cb9716fdbcb44406cc5d3/redis.c#L63):

```
zend_class_entry *spl_ce_RuntimeException = NULL;
```

Similar the [PDO source](https://github.com/php/php-src/blob/php-5.6.23/ext/pdo/pdo.c#L74) I cited in my last comment, they have a [`redis_get_exception_base()`](https://github.com/phpredis/phpredis/blob/363195b97368db1ae43cb9716fdbcb44406cc5d3/redis.c#L375) function that looks up the class on demand; however, PDO uses a static decl on their 
`spl_ce_RuntimeException` variable so not to conflict with SPL.

I've opened https://github.com/phpredis/phpredis/pull/895 to get this fixed upstream.

**Comment by jmikola** [comment]
The upstream PR has been merged, but it appears to be sitting in their `develop` branch and is not yet released. Please follow the phpredis project for updates.

I'm going to close this as there's nothing to be done on our side.
