### ISSUE TITLE
Reference to the other ObjectID or more than 1 ObjectID in the same document

### ISSUE THREAD

**Issue by docchat** [mongodb/mongo-php-driver#356]
Hello!

Here is my environment info:

`$ php -v`
```bash
PHP 7.0.5-4+donate.sury.org~xenial+1 (cli) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

`$ php --ri mongodb`
```bash
mongodb

mongodb support => enabled
mongodb version => 1.1.8
mongodb stability => stable
libmongoc version => 1.3.5
libbson version => 1.3.5

Directive => Local Value => Master Value
mongodb.debug => no value => no value
```

```php
// create document
$author = Authors::find( [ [ 'email' => 'some@email.com' ] ] );
$doc = new stdClass()
$doc->_id = new ObjectID();
$doc->authorId = $author->_id;
```

Before saving the document I see this for `authorId`

```php
string(1199) "object(MongoDB\BSON\ObjectID)#410 (1) {
  ["oid"]=>
  string(24) "57946dbc0ffce21c8c2d24d2"
}
```

after saving and `find` I see this for the same fields:

```php
object(stdClass)#401 (0) {
  }
```
Let me know if you need somethign more from me.
Thank you!

**Comment by docchat** [comment]
I think I found the issue...

The problem that I am using a lot of inherits in my code and usually my Model has a lot of system(framework) related fields which should not be saved in each Document, so I decided to do it by the fastest way and I did this mistake:
```php
$data = json_decode(json_encode($data));
```
And it does not show me the error that I can not serialize `MongoDB\BSON\ObjectID`, I mean it shoed me when I tried to serialize it manually, but did not show error for `json_encode()`.

Sorry - it was not the issue of driver - my fault...

**Comment by jmikola** [comment]
> And it does not show me the error that I can not serialize `MongoDB\BSON\ObjectID`, I mean it shoed me when I tried to serialize it manually, but did not show error for `json_encode()`.

When given an object that does not implement [JsonSerializable](php.net/jsonserializable),  `json_encode()` simply treats it as an array (see: [here](https://github.com/php/php-src/blob/e247e9396106a7e3fad5fdfcbdcdc100c0b89ea5/ext/json/json_encoder.c#L534)), using its properties instead as it would with array keys. Since none of our BSON classes have properties, this results in an empty JSON object.

As @moderndeveloperllc said, we recently implemented supported for normal PHP serialization in the master branch. With [PHPC-459](https://jira.mongodb.org/browse/PHPC-459), we hope to have the classes also implement [JsonSerializable](php.net/jsonserializable). Please follow that issue for progress.
