### ISSUE TITLE
Potential memory corruption php7 + opcache + mongodb

### ISSUE THREAD

**Issue by cb-msales** [mongodb/mongo-php-driver#373]
Hi all,

I'm starting this issue here becasue it looks like our issue is not really caused by the php library itself:

[mongodb/mongo-php-library/issues/216](https://github.com/mongodb/mongo-php-library/issues/216)

The experience suggest that something corrupts the memory causing this problem.

**Comment by jmikola** [comment]
Since mongodb/mongo-php-library#216 already exists, we can consolidate discussion there. There's no need to spread issues across the extension and library GitHub repositories, as that just adds more overhead. If this was JIRA, I'd simply relocate the original issue to the extension project. Unfortunately, GitHub doesn't offer that functionality.

Once we're able to diagnose the issue, a JIRA issue can be created on the PHPC project (for the extension).
