### ISSUE TITLE
No suitable servers found (serverselectiontryonce set): [connection error calling ismaster on <ip>]

### ISSUE THREAD

**Issue by philipbrown** [mongodb/mongo-php-driver#431]
### Description

I'm getting the `No suitable servers found (serverselectiontryonce set): [connection error calling ismaster on <ip>]` error.

### Environment

- PHP 7.0.10 running on AWS.
- driver version => 1.2.0alpha3
- libmongoc version => 1.5.0-rc0
- libbson version => 1.5.0-rc0
- via https://github.com/jenssegers/laravel-mongodb

Let me know if you need any more information or if there is anything you would like me to try 😊

**Comment by jmikola** [comment]
Are you connecting to a single MongoDB node or a replica set?

The "connection error" message should actually read "connection timeout" (per [CDRIVER-1567](https://jira.mongodb.org/browse/CDRIVER-1567), which is fixed in 1.5.0). This is quite possibly a natural network timeout where the driver is not getting a response from the server in the allowed period. The `connectTimeoutMS` URI option is used as a socket IO timeout for these monitoring requests, and libmongoc defaults to 10 seconds if you do not specify a value yourself.

**Comment by philipbrown** [comment]
We're using a replica set.

So your recommendation is to increase the `connectTimeoutMS` option? Do you have any advice on what that should be?

Thank you 😊

**Comment by jmikola** [comment]
Are you getting this exception when attempting to select a primary server? If not, what was the ReadPreference (e.g. "secondary", "secondaryPreferred") used to select the server?

Is the error repeatable, or did this only occur due to a single event (e.g. failover)?

Ten seconds is beyond normal network latency, so this timeout likely means the server is down or there is a network/routing issue. Based on the MongoDB server logs, were any of the replica set members actually down when this was thrown?

Also, I expect this exception is thrown after a ten second delay in your application. If anything, you would want to lower `connectTimeoutMS` to allow the driver to fail sooner if a server cannot be found. Note that this kind of exception may be expected if the replica set is in the process of failing over and you are selecting a primary.

**Comment by philipbrown** [comment]
Ah ok, I see. I'll do some more investigation on my end.

Thank you for your help ❤️

**Comment by jmikola** [comment]
Note: we've just released [1.1.9](https://github.com/mongodb/mongo-php-driver/releases/tag/1.1.9), which includes a fix for the swapped "connection error" and "connection timeout" messages.

**Comment by philipbrown** [comment]
Cool, thank you Jeremy I'll start using that release. We haven't had this error in over a week now so fingers crossed, it's resolved. Thank you for your help 😊
