### ISSUE TITLE
how to install pecl in linux 10.04 lts  ?

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb/mongo-php-driver#439]
I can't install pecl in linux 10.04 lts when i run pecl mongo install  wants me to upgrade my linux but i cant because it is in my production server in cant down it by upgrading please help me if ther is any version for linux 10.04

**Comment by jmikola** [comment]
I'm closing this as a duplicate of https://github.com/mongodb/mongo-php-driver/issues/438.

There are numerous blog posts on the subject of installing PECL (and various packages) on older versions of Ubuntu:

 * http://blog.janjonas.net/2010-08-26/ubuntu-10_04-php-5_3-installin-pecl_http
 * http://askubuntu.com/questions/403327/install-pecl-packages-on-ubuntu
 * http://www.mkfoster.com/2009/01/04/how-to-install-a-php-pecl-extensionmodule-on-ubuntu/

This is not the appropriate forum for general PHP support questions. Please take this to [Stack Overflow] or [Server Fault](http://serverfault.com/). The latter may be more appropriate since this question has more to do with ops than programming.
