### ISSUE TITLE
Possibility to get raw JSON result from MongoDB\Driver\Cursor

### ISSUE THREAD

**Issue by sandrokeil** [mongodb/mongo-php-driver#499]
Does it make sense and is possible to implement a method like `toJson() : string` to the `MongoDB\Driver\Cursor` class? I want to avoid `json_encode($cursor->toArray())` to increase performance and to output the json directly to the client.

I don't know much about the internals, but it would be great to avoid internal calls of `toArray()` and `json_encode` in this new method. Simply return raw MongoDB response which is in JSON?

**Comment by jmikola** [comment]
> Simply return raw MongoDB response which is in JSON?

To clarify, the raw MongoDB response is actually [BSON](http://bsonspec.org/), which does have some differences (i.e. additional types, ordered keys instead of unordered).

You are rightfully concerned about the memory overhead of loading the full result set into an array. A more efficient approach would be to decorate the `MongoDB\Driver\Cursor` object with a custom iterator that converts each element to the desired format. We do this in the MongoDB PHP library to present some command results as custom model classes. Consider [`MongoDB\Model\CollectionInfoCommandIterator`](https://github.com/mongodb/mongo-php-library/blob/1.1.0/src/Model/CollectionInfoCommandIterator.php), which is constructed from [`MongoDB\Operation/ListCollections`](https://github.com/mongodb/mongo-php-library/blob/1.1.0/src/Operation/ListCollections.php#L95). In your case, you could have `current()` map the PHP value through `json_encode()` and return a JSON string for each element. This approach would require you to concatenate those strings into a JSON array manually (i.e. joining with commas and wrapping with square brackets).

The extension also has a [`MongoDB\BSON\toJSON()`](http://php.net/manual/en/function.mongodb.bson-tojson.php) function, which uses libbson directly to convert raw BSON data to JSON. Much like the `jsonSerialize()` methods on our own BSON type classes, this produces [MongoDB Extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/) for the complex BSON types. That said, using `MongoDB\BSON\toJSON()` would first require you to convert the documents back to raw BSON from PHP using [`MongoDB\BSON\fromPHP()`](http://php.net/manual/en/function.mongodb.bson-fromphp.php), which is needless overhead. The `toJSON()` approach might make more sense in the future if we implement an API for accessing the raw BSON through a Cursor (tracking ticket: [PHPC-324](https://jira.mongodb.org/browse/PHPC-324)).

I've created [PHPC-880](https://jira.mongodb.org/browse/PHPC-880) to track the idea. To quote my notes from that issue:

> `MongoDB\Driver\Cursor::toJSON()` would allow obtaining all cursor result documents as JSON without requiring documents to be converted to PHP values and routed through `json_encode()` with a decorating iterator.
>
> This may be redundant with [PHPC-324](https://jira.mongodb.org/browse/PHPC-324), as a raw BSON iterator would make it trivial to create a decorating iterator in userland that invokes `MongoDB\BSON\toJSON()` directly.

I think it would be more worthwhile to implement the raw BSON iterator, as it would address your need in the most efficient manner (skipping PHP entirely in the conversion chain) by way of a decorating iterator, while still supporting other use cases (e.g. implementing `mongodump` in PHP efficiently).

**Comment by jmikola** [comment]
Closing this, as we have linked issues in JIRA for a proposed `MongoDB\Driver\Cursor::toJSON()` API as wells as the raw BSON iterator.
