### ISSUE TITLE
Options "socketTimeoutMS" and "maxTimeMS"

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-driver#510]
Legacy driver supports options "socketTimeoutMS" and "maxTimeMS" in method `\MongoCollection::createIndex()`: http://php.net/manual/ru/mongocollection.createindex.php

But I see that there is no such options in [`createIndexes` command documentation](https://docs.mongodb.com/manual/reference/command/createIndexes/) and such options are not implemented in `CreateIndexes` operation in the MongoDB PHP Lib.

I also don't see this option in any of bulk write operations and in docs for `MongoDB\Driver\BulkWrite`.

So the question is:

1. Does this extension support such options in `createIndexes` command?
2. If extension does not support such options in this command (I beleive so), how to specify max time when creating index?
3. How to specify max time for bulk write operations? Am I understanding this right:
- socket timeout is specified once per connection (`Manager` or `Client`) and exception is thrown on socket timeout for any operation;
- the `WriteConcern`'s option `wtimeout` is the only way to specify max time for bulk writes. But this option is applicable only for `w` > 1.

Thanks in advance.

**Comment by jmikola** [comment]
> Does this extension support such options in `createIndexes` command?

The extension provides three generic methods for executing write operations, queries, and database commands. The actual helper method for `createIndexes` lives in the [PHP library](https://github.com/mongodb/mongo-php-library).

That said, the MongoDB server itself does not presently support execution time limits for write operations (outside of `wtimeout`, which I'll discuss later). The "maxTimeMS" query and command option discussed in the [Terminate Running Operations](https://docs.mongodb.com/manual/tutorial/terminate-running-operations/) manual page only applies to read operations. If you look at the [`createIndexes`](https://docs.mongodb.com/manual/reference/command/createIndexes/) command documentation, you'll see no mention of it.

Therefore, we don't support that option in the library's `createIndexes` command helper. For what it's worth, attempting to pass the option manually in a `createIndexes` command document will produce an error, as show in the following `mongo` shell example:

```
> db.runCommand({createIndexes:"foo",indexes:[{key:{x:1},name:"x_1"}],maxTimeMS:1})
{
	"ok" : 0,
	"errmsg" : "Invalid field specified for createIndexes command: maxTimeMS",
	"code" : 2,
	"codeName" : "BadValue"
}
```

> If extension does not support such options in this command (I beleive so), how to specify max time when creating index?

I'm not aware of any time limit for index creation. You do have the `background` option, which may be used to avoid blocking other database operations; however, the PHP driver will still await a command response from the server. We have no facility in the current driver to apply a socket timeout to individual operations, which you were able to do in the legacy driver. The socket timeout specified when creating the `MongoDB\Driver\Manager` object will always apply.

The subject of per-operation socket timeouts was previously discussed in [PHPC-576](https://jira.mongodb.org/browse/PHPC-576). That "feature" of the legacy driver was often misunderstood (see: [my blog post](http://jmikola.net/blog/mongodb-timeouts/) on the subject) and we decided not to implement it in the new driver. We had the option of implementing it in the 1.1.x series, since we were using PHP's streams API and our own functions for socket communication; however, this is no longer even an option in 1.2+, where our socket communication is handled entirely through libmongoc, which does not allow per-operation socket timeouts.

> How to specify max time for bulk write operations? Is WriteConcern argument "wtimeout" the new maxTimeMS for bulk write operations?

The [`wtimeout`](https://docs.mongodb.com/manual/reference/write-concern/#wc-wtimeout) option for write operations only determines the timeout for replication (based on other write concern options) after a write operation has been successfully applied to a primary. It's generally considered a "soft error", while something like a duplicate key violation would be a hard error.

If you'd like to abort a write operation, I expect you are limited to using the [`killOp`](https://docs.mongodb.com/manual/reference/command/killOp/) command. This is best done through the `mongo` shell, as it has helpers for `killOp` and other functions to return a list of current operations on the server. I've not used this to abort index creations myself, so I'm not sure what state this will leaves the incomplete index. I would not be surprised if the server simply deleted it if the creation operation was killed.

**Comment by petr-buchin** [comment]
@jmikola , thank you very much for such a detailed answer.

I have read your answer and your [blog post](http://jmikola.net/blog/mongodb-timeouts/) and it made my day :) Now it's all clear to me.

But I think that [documentation](http://php.net/manual/ru/mongocollection.createindex.php) for the legacy driver's method `\MongoCollection::createIndex` contains an error, as it says that this method supports `maxTimeMS` option, which, like you said, is only applicable for the read operations.

**Comment by jmikola** [comment]
> But I think that [documentation](http://php.net/manual/ru/mongocollection.createindex.php) for the legacy driver's method `\MongoCollection::createIndex` contains an error, as it says that this method supports `maxTimeMS` option, which, like you said, is only applicable for the read operations.

This appears to be a regression in the server, as `maxTimeMS` was originally supported when `createIndexes` was introduced in server 2.6. I've opened [PHP-1524](https://jira.mongodb.org/browse/PHP-1524) to look into this further.

Interestingly, the option was never discussed in our [Index Management specification](https://github.com/mongodb/specifications/blob/master/source/index-management.rst), which is implemented by the new library. It's possible that the functionality was intentionally removed in the server, which might explain why it's missing from the spec.

**Comment by jmikola** [comment]
I [confirmed](https://jira.mongodb.org/browse/PHP-1524?focusedCommentId=1478349&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1478349) that this was actually a regression in server 3.4.0-rc0. The legacy PHP documentation can remain in place.

Additionally, I've opened [PHPLIB-254](https://jira.mongodb.org/browse/PHPLIB-254) so that we can support `maxTimeMS` for index creation in the new library.

**Comment by petr-buchin** [comment]
@jmikola , thank you! 
As far as I understand, there is a possibility that PHP applications, that use legacy driver with MongoDB server 3.4, will receive an exception in places where they use `maxTimeMS` option in `\MongoCollection::createIndex()` method?
Do you know what version of the server will receive a fix for that? And what will be that fix - allowing option and ignoring it, or support of this option?

**Comment by jmikola** [comment]
> As far as I understand, there is a possibility that PHP applications, that use legacy driver with MongoDB server 3.4, will receive an exception in places where they use `maxTimeMS` option in `\MongoCollection::createIndex()` method?

That's correct.

> Do you know what version of the server will receive a fix for that? And what will be that fix - allowing option and ignoring it, or support of this option?

The exception for using `maxTimeMS` with `createIndexes` appears to be an unintentional regression of validation implemented in [SERVER-769](https://jira.mongodb.org/browse/SERVER-769). I've opened [SERVER-27711](https://jira.mongodb.org/browse/SERVER-27711) to report this, but we'll have to watch that ticket for further updates on a fix.
