### ISSUE TITLE
Changed behaviour between 1.2.2 and 1.2.3

### ISSUE THREAD

**Issue by mrohnstock** [mongodb/mongo-php-driver#517]
### Description

v1.2.3 can't handle object/array-keys in embedded documents, which worked until v1.2.2.

### Environment

* php 7.1.1 on archlinux x86_64
* mongodb 3.4.1
* installed mongodb 1.2.2 / 1.2.3 through pecl with:

```
$ sudo pecl install mongodb-1.2.2
$ php -i | grep -E 'mongodb|libmongoc|libbson'
/etc/php/conf.d/mongodb.ini,
mongodb
mongodb support => enabled
mongodb version => 1.2.2
mongodb stability => stable
libmongoc version => 1.5.0
libbson version => 1.5.0
mongodb.debug => no value => no value

----

$ sudo pecl install mongodb-1.2.3
$ php -i | grep -E 'mongodb|libmongoc|libbson'
/etc/php/conf.d/mongodb.ini,
mongodb
libbson bundled version => 1.5.3
libmongoc bundled version => 1.5.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
mongodb.debug => no value => no value
```

### Test Script

**FYI**: The following document got created with the [c++-legacy driver of mongodb](https://github.com/mongodb/mongo-cxx-driver/releases/tag/legacy-1.1.2) and I already used these document in php for a very long time (maybe the document is not well formed, or something...?).

The following images are from the latest [php-mongodb-admin](https://github.com/jwage/php-mongodb-admin) with the [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) to get it working with the new php-mongodb driver.

I want also to note, the only thing, that changed between these two images is php-mongodb from 1.2.2 -> 1.2.3, nothing else.

_(Is there a way to dump / restore just one document for test purposes? I would dump this document, if possible, to make this thing much easier to check :))_

### Expected and Actual Behavior

This is the output of v1.2.2 (and older):

![1 2 2](https://cloud.githubusercontent.com/assets/823072/22250649/fa5475d8-e247-11e6-9dfd-76218059d6a9.jpg)

And this is the changed behaviour with v1.2.3:

![1 2 3](https://cloud.githubusercontent.com/assets/823072/22250483/59ba7eb0-e247-11e6-9bd8-bb13cece36b0.jpg)

Is there now a incompability change between the c++-legacy driver of mongodb and php-mongodb?

Thanks :)!

**Comment by jmikola** [comment]
> The following document got created with the c++-legacy driver of mongodb and I already used these document in php for a very long time (maybe the document is not well formed, or something...?).

The change in behavior you're seeing is due to [PHPC-883](https://jira.mongodb.org/browse/PHPC-883), which was implemented to comply with the [BSON corpus specification](https://github.com/mongodb/specifications/blob/master/source/bson-corpus/bson-corpus.rst). In the [BSON spec](http://bsonspec.org/spec.html), encoded arrays and objects both have a null-terminated string for their field name. In canonical BSON, the field name for each array element should be a  numeric string ("0", "1", "2", etc.). One of the BSON corpus tests was to ensure that BSON arrays are always decoded as an actual array (sequentially indexed, starting at zero), so our fix entailed disregarding the keys found in BSON and relying on PHP to append each element to an array.

I believe the use of numeric strings for array elements also has implications for the [dot notation](https://docs.mongodb.com/manual/core/document/#arrays) in MongoDB's query language. If the legacy C++ driver was actually storing names for the element indexes instead of numeric strings, I'd be curious to know if you can still access those properties by their array index in the shell (e.g. `cards.0.0`).

You should consider using an embedded document instead of an array in your schema if non-numeric field names are needed for these elements.

> Is there now a incompatibility change between the c++-legacy driver of mongodb and php-mongodb?

It appears so, although I think this is not just limited to the PHP driver. I don't think this is something that will be resolved in the legacy C++ driver. [libbson](https://github.com/mongodb/libbson), which is used by the new C++ driver, also allows any string key to be specified for an array elements (see: [here](https://github.com/mongodb/libbson/blob/e83e9d833c8a8fae269404567b00561eb42404fd/tests/test-bson.c#L273)), so it may still be up to users to specify incrementing, numeric strings. As it relates to the BSON corpus specification, compliant drivers must ensure that canonical numeric keys are used during decoding.

> (Is there a way to dump / restore just one document for test purposes? I would dump this document, if possible, to make this thing much easier to check :))

The [MongoDB\BSON functions](http://php.net/manual/en/ref.bson.php) can be used to convert a binary string of BSON data to a PHP or JSON value (and vice versa).

**Comment by mrohnstock** [comment]
> I'd be curious to know if you can still access those properties by their array index in the shell (e.g. `cards.0.0`).

Yep:

```
> var sale = db.sale.findOne( { _id : ObjectId("527f3d8602c38cb0a49e343b") });
> sale.cards
[
        [
                "Postkarte_Kramp_Agritechnica_DE.jpg",
                "default",
                "",
                1,
                1384073535,
                34,
                "normal"
        ]
]
> sale.cards.0.0
2017-01-24T19:41:10.069+0100 E QUERY    [thread1] SyntaxError: missing ; before statement @(shell):1:10
> sale.cards[0][0]
Postkarte_Kramp_Agritechnica_DE.jpg
```

I will try tomorrow to migrate these kind of `array` into the new form, with php directly, as the program, which used the legacy c++ driver is already obsolete and won't get used since this year.

Thanks so far Jeremy :)!

**Comment by jmikola** [comment]
> ```
> > sale.cards.0.0
> 2017-01-24T19:41:10.069+0100 E QUERY    [thread1] SyntaxError: missing ; before statement @(shell):1:10
> > sale.cards[0][0]
> > Postkarte_Kramp_Agritechnica_DE.jpg
> ```

This is actually testing how the BSON is decoded to a Javascript value in the shell. I actually meant testing dot notation in query criteria, such as:

```
> db.sale.findOne({ "sale.cards.0.0": "Postkarte_Kramp_Agritechnica_DE.jpg" });
```

That said, it looks like the shell also converts the BSON array to a Javascript array and forsakes the original field names.

**Comment by mrohnstock** [comment]
Oh I see, second try with:

```
> db.sale.findOne( { "cards.0.0" : "Postkarte_Kramp_Agritechnica_DE.jpg" });
null
> db.sale.findOne( { "cards.0.name" : "Postkarte_Kramp_Agritechnica_DE.jpg" });
null
```

No, nothing :(.

**Comment by mrohnstock** [comment]
Alright, migrated everything and all is good now :) Thanks for everything!

**Comment by jmikola** [comment]
@mrohnstock: It's a bit late, but I've amended the [1.2.3 release notes](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.3) to call more attention to this change. I will follow-up on the [mongodb-user post](https://groups.google.com/d/msg/mongodb-user/qzn-M2av5UY/Xoj9DrJ9CAAJ) as well.
