### ISSUE TITLE
fatal error: 'openssl/sha.h' file not found on installation

### ISSUE THREAD

**Issue by dendisuhubdy** [mongodb/mongo-php-driver#523]
```
private/tmp/pear/install/mongodb/src/libbson/src/bson/ -DHAVE_CONFIG_H -g -O2 -D_THREAD_SAFE -pthread -c /private/tmp/pear/install/mongodb/src/libmongoc/src/mongoc/mongoc-crypto-openssl.c  -fno-common -DPIC -o src/libmongoc/src/mongoc/.libs/mongoc-crypto-openssl.o
/private/tmp/pear/install/mongodb/src/libmongoc/src/mongoc/mongoc-crypto-openssl.c:24:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
```

**Comment by dendisuhubdy** [comment]
Do this

```
$ cd /usr/local/include 
$ ln -s ../opt/openssl/include/openssl .
```

**Comment by jmikola** [comment]
The driver uses PHP's own [`PHP_SETUP_OPENSSL()`](https://github.com/php/php-src/blob/php-7.1.1/acinclude.m4#L2310) Autotools function to detect OpenSSL, so I'm curious how the build process would have found OpenSSL when running `./configure`  but not have added the appropriate include path so that the headers could be found at compile time.

Can you elaborate on your environment? It's missing quite a bit of details requested in the new issue template. I'd just like to determine whether or not this is a bug in our build process.

**Comment by dendisuhubdy** [comment]
I'm using Mac OSx Sierra 10.12. I override the openssl installation by doing a brew.
