### ISSUE TITLE
Integer types missing NumberLong

### ISSUE THREAD

**Issue by Roycohen** [mongodb/mongo-php-driver#525]
HI There,

I have an issue with strong types when saving to DB.
I'm using findAndModify command and I've checked that I'm inserting fields as integers but when looking at them, I don't see them as NumberLong in the DB.
Can you please help me understand what is going on.

libbson bundled version => 1.5.4
libmongoc bundled version => 1.5.4
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
mongodb.debug => no value => no value

**Comment by jmikola** [comment]
[NumberLong](https://docs.mongodb.com/manual/core/shell-types/#numberlong) and [NumberInt](https://docs.mongodb.com/manual/core/shell-types/#numberint) are wrapper objects in the shell to denote the 64-bit and 32-bit integer types in [BSON](http://bsonspec.org/spec.html), respectively.

When the driver encodes a PHP integer to BSON ([here](https://github.com/mongodb/mongo-php-driver/blob/1.2.5/src/bson.c#L1220)), we use a [macro](https://github.com/mongodb/mongo-php-driver/blob/1.2.5/src/bson.c#L40) that writes a 64-bit or 32-bit integer depending on the range of the PHP integer value. This is analogous to the server's behavior, where results of integer computation (e.g. from an `$inc`) will use the smallest type able to contain the value and roll over to the large type as needed.

When decoding a BSON integer to a PHP value, [`php_phongo_bson_visit_int32()`](https://github.com/mongodb/mongo-php-driver/blob/1.2.5/src/bson.c#L557) converts 32-bit integers to a PHP integer as there is no risk of overflow. By contrast, [`php_phongo_bson_visit_int64()`](https://github.com/mongodb/mongo-php-driver/blob/1.2.5/src/bson.c#L609) uses [several macros](https://github.com/mongodb/mongo-php-driver/blob/1.2.5/phongo_compat.h#L146) to conditionally throw an exception if a 64-bit BSON integer cannot be represented as a PHP integer on 32-bit platforms. For 64-bit platforms, the code path is as direct as `php_phongo_bson_visit_int32()` as there is no risk of overflow.

This means that the driver cannot work with BSON integers that are outside the range of 32-bit signed integers on a 32-bit platform. This limitation is intentional, as we did not want to repeat the design of the legacy driver, which had [MongoInt32](http://php.net/manual/en/class.mongoint32.php) and [MongoInt64](http://php.net/manual/en/class.mongoint64.php) classes, whose use was controlled by [`mongo.long_as_object`](http://php.net/manual/en/mongo.configuration.php#ini.mongo.long-as-object) and [`mongo.native_long`](http://php.net/manual/en/mongo.configuration.php#ini.mongo.native-long) INI settings.

**Comment by tonyzheng121** [comment]
if we have to use NumberLong, do you have any other solutions?

**Comment by jmikola** [comment]
@tonyzheng121: I've opened [PHPC-1949](https://jira.mongodb.org/browse/PHPC-1949) to consider allowing explicit construction of Int64 objects. Please read through that issue to note some of the caveats. That said, if you urgently need to construct an Int64 object today you can certainly do so via `unserialize()`, as demonstrated in some of our internal tests (e.g. [`bson-int64-serialization-001.phpt
`](https://github.com/mongodb/mongo-php-driver/blob/master/tests/bson/bson-int64-serialization-001.phpt)). That is hardly a user-friendly API, but it should serve as a workaround for the time being.

In the future, please open a new issue instead of commenting on an old, closed issue. You can always link back to the older issues for context in your new issue. This likewise applies to the other comment you left in https://github.com/mongodb/mongo-php-driver/issues/240#issuecomment-896712717.

**Comment by aleshaczech** [comment]
Hi, I wonder if this also fits my issue:

I am trying to write to a MongoDB collection that has `$jsonSchema` validator set. The server is rejecting the write with "document failed validation" exception.

The relevant part of the schema is:
```json
{
  "value": {
    "bsonType": "long",
    "minimum": 0
  }
}
```

When I attempt to write a "small" PHP value (e.g. 0), the exception occurs. When I try to write a number beyond the range of 32-bit integer, the write succeeds. Apparently it's caused by PHP deciding whether to use `int` or `long`. However, I need to enforce `long` because of the JSON Schema.

I succeeded using two workarounds:
* the one @jmikola mentioned above with `Int64` that enforces `long` to be used;
* or I can use the type enumeration `anyOf` in the JSON Schema to allow both `int` and `long` (https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/).

I am not sure if there's any other way, e.g. using Extended JSON somehow? Have I missed something?

Thanks!

**Comment by jmikola** [comment]
@aleshaczech: I followed up in [PHPC-1949](https://jira.mongodb.org/browse/PHPC-1949).

To summarize for anyone following along here:

 * Using the Int64 class is viable, but it is a very tactical approach and would also need to be done each time a 32-bit value is read and re-written to the database (easier for an ODM to handle than an application directly using the driver).
 * MongoDB's JSON schema implementation does not support the original [`integer` type](https://json-schema.org/understanding-json-schema/reference/numeric.html#integer) (see: [`$jsonSchema: Omissions](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#omissions)), but using `bsonType` with `[ int, long ]` would be more concise than `anyOf` (see: [`$jsonSchema: Available Keywords](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#available-keywords)).
