### ISSUE TITLE
Sorting command options

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-driver#565]
For now `\MongoDB\Driver\Command` requires the command name to be the first key in options, passed to it.

For example:

```php
// Will work
$command = new \MongoDB\Driver\Command([
    'aggregate' => 'my_collection_name',
    'pipeline' => $pipeline,
]);

// Will NOT work
$command = new \MongoDB\Driver\Command([
    'pipeline' => $pipeline,
    'aggregate' => 'my_collection_name',
]);
```

This leads to some complexities when writing userland driver library.
For example, in my [library](https://github.com/tequila/mongodb-php-lib) I use modification of the Symfony [OptionsResolver](https://github.com/symfony/options-resolver) component, but I cannot simply use it as is, since it may reorder options, and command name will not be the first key in a resulting array.

Do you have plans to add support for **unordered** options in `MongoDB\Driver\Command`?
Or maybe it's possible to add something like described below to the `MongoDB\Driver\Command` without breaking BC, supporting both forms of command options?

```php
$command = new \MongoDB\Driver\Command([
    'command' => 'aggregate',
    'collection' => 'my_collection_name',
    'pipeline' => $pipeline,
]);
```

**Comment by jmikola** [comment]
> For now `\MongoDB\Driver\Command` requires the command name to be the first key in options, passed to it.

This is actually a requirement of the MongoDB server, which checks the first field in a BSON document when parsing a command. The `MongoDB\Driver\Command` constructor has very little logic and merely [converts the array argument to BSON](https://github.com/mongodb/mongo-php-driver/blob/1.2.8/src/MongoDB/Command.c#L64).

Internally, the server is working on a new [protocol](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/) for issuing commands; however, the current version of that spec still states that command names will be inferred from the first field in a document.

> Or maybe it's possible to add something like described below to the MongoDB\Driver\Command without breaking BC, supporting both forms of command options?

Since the driver has no special knowledge of command syntax, the example you proposed isn't feasible. We would need to add logic to detect the "command" and "collection" fields, create a new array with them combined as a single key/value pair, and then merge the remaining keys. This would require a whitelist of database commands, which would then need to be regularly updated to accommodate new server versions. And there would be edge cases for commands that don't follow the `{ commandName: <collectionName> }` convention, such as [`createUser`](https://docs.mongodb.com/manual/reference/command/createUser/) and [`group`](https://docs.mongodb.com/manual/reference/command/group/). Ultimately, I think this would be better handled in userland.

**Comment by jmikola** [comment]
> For example, in my [library](https://github.com/tequila/mongodb-php-lib)

By the way, I'd be happy to add your library to https://docs.mongodb.com/ecosystem/drivers/php-libraries/ when you feel it's stable enough and has enough documentation for new users to pick up. We're a bit short on projects using the new driver, and it'd be great to promote alternative libraries (that was one of the goals all along with the split architecture).

**Comment by petr-buchin** [comment]
@jmikola , thank you very much for such a great explanation!
I understand that there are commands that don't follow `{commandName: <collectionName>}` convention, I  simply thought about required command options, like `collectionName` for commands that follow this convention.
Anyway, if this is a requirement of the server, there is nothing to talk about :)

> By the way, I'd be happy to add your library to https://docs.mongodb.com/ecosystem/drivers/php-libraries/ when you feel it's stable enough and has enough documentation for new users to pick up. 

I would be more than happy, but for now library is not stable enough and not well documented :)
