### ISSUE TITLE
Mongodb authentication failed in php7

### ISSUE THREAD

**Issue by karsa87** [mongodb/mongo-php-driver#585]
Hy anyone,

I create new connection to mongodb from php7 
but I get error : **"authectication fail"** 

this script create new connection :

$conn = new Client("mongodb://user:password@host:port");
$db = $conn->selectDatabase("DATABASE_NAME");
$collection = $db->selectCollection("COLLECTION_NAME");
$data = $collection->find();

Is there a solution to my problem ? Is there anybody who can help me ?

We can discuss via email, this my email karsaaif87@gmail.com

Thank you,

**Comment by jmikola** [comment]
A few things to check would be:

 * If the username or password contains special characters (e.g. something other than alpha-numeric characters), you should encode each string with `rawurlencode()` as discussed in the [`MongoDB\Driver\Manager::__construct()`](http://php.net/manual/en/mongodb-driver-manager.construct.php) and [`MongoDB\Client::__construct()`](https://docs.mongodb.com/php-library/master/reference/method/MongoDBClient__construct/) documentation. Alternatively, you can specify the username and password in the URI options array (second parameter) in lieu of the URI string, which will not require any encoding.
 * Since you are not specifying an authentication source, the driver defaults to authenticating against the "admin" database. Depending how the user is configured, you may need to specify a difference database via the `authSource` URI option.
 * By default, the [`authMechanism`](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authMechanism) defaults to [`SCRAM-SHA-1`](https://docs.mongodb.com/manual/core/security-scram-sha-1/#authentication-scram-sha-1) for MongoDB 3.0+ and [`MONGODB-CR`](https://docs.mongodb.com/manual/core/security-mongodb-cr/#authentication-mongodb-cr) for earlier versions. Ensure that this is consistent with your database configuration.

Lastly, I'd suggest attempting to authenticate with identical options and credentials via the `mongo` shell to rule out any issues with the PHP driver.

**Comment by jmikola** [comment]
Closing this out due to inactivity. Feel free to followup if the issue persists.
