### ISSUE TITLE
OpenSSL version >= 1.1 is not supported

### ISSUE THREAD

**Issue by schwenni** [mongodb/mongo-php-driver#612]
### Description
install mongodb failed ...  
because of....

....
checking whether to use system libmongoc... no
checking configuring libmongoc... ...
checking for pkg-config... /usr/bin/pkg-config
configure: error: OpenSSL version >= 1.1 is not supported.

### Environment
Ubuntu 16.04 
OpenSSL 1.1.0f  25 May 2017

/etc/php/7.0/cli/conf.d/20-mongodb.ini,
mongodb
mongodb support => enabled
mongodb version => 1.1.5
mongodb stability => stable
libmongoc version => 1.3.3
libbson version => 1.3.3
mongodb.debug => no value => no value

**Comment by mookfist** [comment]
I have this problem too, Ubuntu 16.04:

# apt-cache show libssl-dev
Package: libssl-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 6949
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: same
Source: openssl
Version: 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1
Depends: libssl1.1 (= 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1)
Recommends: libssl-doc
Description-en: Secure Sockets Layer toolkit - development files
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains development libraries, header files, and manpages for libssl
 and libcrypto.
Description-md5: 27044468897c45b271f879c7c6e135fe
Homepage: https://www.openssl.org/

**Comment by moderndeveloperllc** [comment]
@schwenni  You are using a rather old version of the extension. This issue was [fixed in libmongoc 1.4.0](https://github.com/mongodb/mongo-c-driver/releases?after=1.4.1). Is there a particular reason why y'all are not using the 1.2.x versions of this extension? If you are able to add PPAs, you might want to look into @oerdnj's [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=xenial) which is the gold standard when is comes to PHP on Linux. He has the latest 1.2.9 version that I've been using just fine with PHP 7.1 and PHP 5.6.

@mookfist What's your PHP version and what version of the extension are you attempting to install?

**Comment by scopenco** [comment]
The same problem exists on Debian 9.2.
```
# pecl install mongodb-1.3.4
downloading mongodb-1.3.4.tgz ...
Starting to download mongodb-1.3.4.tgz (848,798 bytes)
......done: 848,798 bytes
412 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
building in /tmp/pear/temp/pear-build-rootouEkFG/mongodb-1.3.4
running: /tmp/pear/temp/mongodb/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20131226
checking for PHP installed headers prefix... /usr/include/php/20131226
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking whether to use system default cipher list instead of hardcoded value... no
checking PHP version... 50632
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking whether to use system libbson... no
checking whether to use system libmongoc... no
checking configuring libmongoc... ...
checking for pkg-config... no
configure: error: Cannot find OpenSSL's libraries
ERROR: `/tmp/pear/temp/mongodb/configure --with-php-config=/usr/bin/php-config' failed
```

libssl1.1 conflicting with libssl1.0 that is required by this module.

**Comment by jmikola** [comment]
> The same problem exists on Debian 9.2

@scopenco: You're paste does not indicate the same problem as the OP. In the OP's case, `pkg-config` finds OpenSSL 1.1, which was not supported in version 1.1.5 of this driver:

```
checking for pkg-config... /usr/bin/pkg-config
configure: error: OpenSSL version >= 1.1 is not supported.
```

In your case, PHP's [`PHP_SETUP_OPENSSL()`](https://github.com/php/php-src/blob/php-5.6.32/acinclude.m4#L2309) autotools function fails to detect OpenSSL at all. Since you don't have `pkg-config` available, PHP falls back to searching a list of known directories, which may not be reliable. As noted in our [PECL install instructions](http://php.net/manual/en/mongodb.installation.pecl.php), you should install `pkg-config` if possible.

**Comment by scopenco** [comment]
@jmikola thank you! pkg-config fixed the problem.

**Comment by jmikola** [comment]
Closing this out, as recent versions of the driver should have no problems building against OpenSSL 1.1+.
