### ISSUE TITLE
1.3.0beta1 Windows: HAVE_SOCKLEN_T macro redefinition

### ISSUE THREAD

**Issue by Jan-E** [mongodb/mongo-php-driver#629]
https://github.com/mongodb/mongo-php-driver/commit/0555447041b945d97e411cf7699a15fddcb7b4bc added a check to see if socklen_t was present in WS2tcpip.h. It is:

`typedef int socklen_t;
`

Nevertheless the check evaluates as false and adds a (wrong) #DEFINE HAVE_SOCKLEN_T 0 macro redefinition to main/config.w32.h

See my inline comments as well: https://github.com/mongodb/mongo-php-driver/commit/0555447041b945d97e411cf7699a15fddcb7b4bc#commitcomment-23597703

IMHO is it safe to assume that every supported Windows OS has a socklen_t, because it is a standard definition in config.w32.h. For PHP Master the template for config.w32.h can be found here:

https://github.com/php/php-src/blob/master/win32/build/config.w32.h.in#L147

**Comment by Jan-E** [comment]
See the build logs of the 'official' Windows distro as well:
http://windows.php.net/downloads/pecl/releases/mongodb/1.3.0beta1/logs/

**Comment by jmikola** [comment]
Thanks for reporting this! I have noticed the build warnings locally for some time, but I was unsuccessful in tracing the root cause and it didn't interfere with the DLL compilations and my runtime testing so I didn't dwell on it.

This seems like something we can get fixed before 1.3.0. I've opened [PHPC-994](https://jira.mongodb.org/browse/PHPC-994) to track it.

**Comment by Jan-E** [comment]
Closing because https://jira.mongodb.org/browse/PHPC-994 has been opened.

**Comment by Jan-E** [comment]
As a BTW: the check is not needed, mongoc_opts.MONGOC_HAVE_SOCKLEN can always be set to 1 on Windows.
