### ISSUE TITLE
1.2.10 breaks Travis builds

### ISSUE THREAD

**Issue by Majkl578** [mongodb/mongo-php-driver#649]
Hello.
as1.2.10 was released today, it started breaking Travis builds using this extension from PECL.
This is caused by BC break in cbb5f9f1f2810ebf1f9a086f2d8978b37633d30f which addresses API/ABI break in PHP 7.2 RC phase introduced in https://github.com/php/php-src/commit/bdd56f31078bf1f34341943603cf6aaa72e0db5c#diff-05931d95f4541dc2f528625e662a307c.
Travis is still running on PHP 7.2.0beta3 and this extension fails to compile there.
Here's a failing job for Doctrine: https://travis-ci.org/doctrine/data-fixtures/jobs/273067384#L1141

**Comment by jmikola** [comment]
I can look into amending the conditional in cbb5f9f1f2810ebf1f9a086f2d8978b37633d30f to differentiate between PHP 7.2 RC1 and earlier versions, but I think it would be worthwhile to request that Travis CI upgrade their PHP 7.2 environment to RC1 (if you've not already done so).

As an aside, I imagine we have a number of internal PHP version checks that may fail on historic beta versions.

**Comment by Majkl578** [comment]
Well, Travis is not _that_ fast with updating versions. There is already a PR for newer version here: https://github.com/php-build/php-build/pull/474. But until it gets merged, binaries rebuilt and distributed, this is unfortunately a blocker.

> As an aside, I imagine we have a number of internal PHP version checks that may fail on historic beta versions.

World would be much happier place if there were no BC breaks in beta/RC versions... 😐

**Comment by jmikola** [comment]
Tracking in [PHPC-1009](https://jira.mongodb.org/browse/PHPC-1009).

**Comment by jmikola** [comment]
@Majkl578: I spoke with @derickr about the timelib change and he pointed out that `TIMELIB_VERSION` is not suitable to use for checking ABI (see: https://github.com/mongodb/mongo-php-driver/pull/652#discussion_r138065593). Rather than create a 1.2.11 release with a hackish workaround, and then revert that with a later 1.2.12 release, I'd like to wait this out until Travis CI is updated to 7.2 RC1.

I see that https://github.com/php-build/php-build/pull/474 was merged over the weekend, so hopefully that update will be imminent.

**Comment by jmikola** [comment]
Travis is now using PHP 7.2 RC1, so I will resolve this.

**Comment by Majkl578** [comment]
Awesome, sorry for extra work and thanks!
