### ISSUE TITLE
Problems with scaling mongodb connections

### ISSUE THREAD

**Issue by sriranjan** [mongodb/mongo-php-driver#662]
### Description

We are running php-mongodb 1.2.3 behind apache on a prod environment. One of our clusters is running mongodb 3.2.11 as a replica set. When our traffic peaks, we see the number of connections jump from 8k to 20k on each of these machines. Although the mongodb machines are capable of handling 30k connections, we have set 20k to be the limit. Once it reaches this limit, we start seeing 'no server found' errors. The traffic jumps usually by ~30%. Reading through the docs, it looks like the library is not using the connection pool mode offered by libmongoc. Is there any way for us to reduce the number of connections the apache processes are consuming? Moving to a sharded cluster is not an option right now.

### Environment

What operating system and PHP version are you using? Mention if PHP was
installed through a third-party bundle (e.g. MAMP, XAMPP) and report its version
if applicable.

Centos - 6.4
Apache - 2.4
PHP 5.4
MongoDB - 3.2.11
Php mongodb - 1.2.3

**Comment by jmikola** [comment]
> it looks like the library is not using the connection pool mode offered by libmongoc

The connection pool implemented by libmongoc is only relevant for multi-threaded drivers. As PHP's architecture is single-threaded, the best we can do is persist libmongoc client objects, each of which will maintain at-most one connection per server in the topology/cluster. If we did attempt to use libmongoc's connection pool API, the driver would create one set of connections exclusively for monitoring, and a second set (the "pool") for application usage. That pool size would likely never exceed one, but each PHP worker would effectively double its number of connections.

Although PHP may be configured run in a multi-threaded environment as an Apache module, we still do not have a mechanism for sharing resources across multiple PHP workers (i.e. threads).

Ultimately, your connection utilization in a PHP environment will come down to the product of `numAppServers` × `numRequestWorkersPerAppServer`. Given that, there are a few possibilities:

 * Limit the number of active request workers across the application.
 * Architect the application so that not every request opens a database connection, and limit requests requiring a database connection to a subset of the application servers.
 * Introduce `mongos` nodes on each application server and configure the application to connect through them. While this would require setting up the basics for a shard cluster (e.g. config servers), you would not necessarily need to shard your data and could utilize your existing replica set as the one and only shard.
 * Investigate community-developed tools for load balancing or connection proxying. One such tool I'm aware of is [dvara](http://blog.parse.com/learn/engineering/dvara/), which was developed by Parse. Note that each tool will likely have some shortcomings or compromises, and are not guaranteed to work with each driver or future versions of MongoDB if the wire protocol changes.
 * Migrate the application in whole or part to a different language whose architecture would support connection pooling.

I'm not suggesting that all of these are viable options for you, but those are the possible approaches to mitigating the problem off the top of my head.

AFAIK, PHP.net's own article on [Persistent Connections](http://php.net/manual/en/features.persistent-connections.php), which is mostly written from the context of its SQL driver extensions, concurs with what I've written above. I don't believe this problem is unique to the MongoDB driver.

**Comment by sriranjan** [comment]
Thanks for the thoughtful and detailed answer @jmikola. We are trying to see if we can use haproxy to handle the connections for us.

**Comment by jmikola** [comment]
Beware that haproxy may conflict with the driver's own [server discovery and monitoring](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst), especially if you're connecting to a replica set. Googling for "mongodb haproxy" turns up several blog posts on the subject.

If you do run into trouble, I would suggest looking into using `mongos` as a proxy and registering the replica set as the one and only shard. That would give you the benefit of having `mongos` proxy connections while avoiding any incompatibility driver monitoring (since the SDAM spec does know how to work with mongos).
