### ISSUE TITLE
Build from source faild

### ISSUE THREAD

**Issue by lichunqiang** [mongodb/mongo-php-driver#733]
### Description

When I build the source followed the [CONTRIBUTING.md](https://github.com/mongodb/mongo-php-driver/blob/master/CONTRIBUTING.md) step by step, failed to exec `make all`

The error message:

```
mongo-php-driver/src/libbson/src/bson/bson-version.h:49:1: error：expected identifier or ‘(’ before ‘)’ token
```

The the file of line 49:

```
/**
 * BSON_MICRO_VERSION:
 *
 * BSON micro version component (e.g. 3 if %BSON_VERSION is 1.2.3)
 */
#define BSON_MICRO_VERSION (0
)

```
What should can i do for this? Or I had missing some operations?

My command exec:

```
$ git clone https://github.com/mongodb/mongo-php-driver.git
$ cd mongo-php-driver
$ git submodule update --init
$ phpize
$ ./configure --enable-developer-flags
$ make clean
$ make all
```

**Comment by jmikola** [comment]
I was not able to reproduce this error using the same build steps in my Ubuntu 16.04 environment with PHP 7.2.0 and Autoconf 2.6.9. The last step of `./configure` should have it output the following files for bundled versions of libmongoc and libbson:

```
config.status: creating ./src/libmongoc/src/mongoc/mongoc-config.h
config.status: creating ./src/libmongoc/src/mongoc/mongoc-version.h
config.status: creating ./src/libbson/src/bson/bson-config.h
config.status: creating ./src/libbson/src/bson/bson-version.h
```

`BSON_MICRO_VERSION` should be defined on a single line:

```
#define BSON_MICRO_VERSION (0)
```

If a line break character is sneaking into `BSON_RELEASED_MICRO_VERSION`, that may be due to the parsing in [`build/autotools/Versions.m4`](https://github.com/mongodb/libbson/blob/1.9.0/build/autotools/Versions.m4). Looking at the https://github.com/mongodb/libbson/commit/01f21fee773177a95c830c3c82ec6dfd7b871429, it looks like a trailing newline character was also introduced with the 1.9.0 tag, as the `VERSION_RELEASED` file that is parsed typically ends without a newline.

What environment are you using? This is the first bug report we've seen where the build process failed in this manner; however, [1.4.0beta1](https://pecl.php.net/package/mongodb/1.4.0beta1) is also the only released version of the driver with libbson 1.9.0, so it's possible that enough folks just haven't tested it yet.

@ajdavis: Can you also chime in here? I assume the trailing newline was a mistake, as it was removed again in https://github.com/mongodb/libbson/commit/a2320310fcfa46f41d316129ef7fa255fbe8f83e. In any event, I imagine we'd want to ensure this is corrected in 1.9.1 (for both libbson and libmongoc).

**Comment by ajdavis** [comment]
The Versions.m4 parsing is intended to be robust, no matter whether there's a trailing newline or not in the version files.

**Comment by lichunqiang** [comment]
Hi @jmikola & @ajdavis 

As @jmikola  mentioned about this commit https://github.com/mongodb/libbson/commit/01f21fee773177a95c830c3c82ec6dfd7b871429 I just modify `libbson/VERSION_CURRENT` & `libbson/VERSION_RELEASED` removed the trailing newline in the file, finally make successed

**Comment by jmikola** [comment]
@lichunqiang: What environment are you using to build the driver? Additionally, what version of Autoconf  and Automake are you using (check with `autoconf --version` and `automake --version`).

@ajdavis: When building the driver myself with libbson 1.9.0, I do end up with `#define BSON_MICRO_VERSION (0)` (no line breaks); however, I noticed that if I run the [piped commands used to assign `BSON_MICRO_VERSION`](https://github.com/mongodb/libbson/blob/1.9.0/build/autotools/Versions.m4#L6) manually I do see a trailing newline:

```
$ (cat src/libbson/VERSION_CURRENT; echo) | cut -d- -f1 | cut -d. -f3
0

$
```

Contrast this with running the [piped commands used to assign `BSON_RELEASED_MICRO_VERSION`](https://github.com/mongodb/libbson/blob/1.9.0/build/autotools/Versions.m4#L18) on the same input file with the trailing line break:

```
$ cut -d- -f1 src/libbson/VERSION_CURRENT | cut -d. -f3
0
$
```

As for the difference between these piped command sequences, I believe `cat` and `echo` were added to purposefully add a line break for HP-UX compatibility in https://github.com/mongodb/libbson/commit/e07f7b89ec018a532f1d79169207f72f8660bb56. If the input file already has a line break, I expect that would cause the input to the first `cut` command to have two trailing line breaks instead.

While attempting to research how `AC_SUBST()` interacts with newlines, I noted that [7.2 Setting Output Variables](https://www.gnu.org/software/autoconf/manual/autoconf.html#Setting-Output-Variables) states:

> This means that AC_OUTPUT replaces instances of ‘@variable@’ in input files with the value that the shell variable variable has when AC_OUTPUT is called. _The value can contain any non-NUL character, including newline._ If you are using Automake 1.11 or newer, for newlines in values you might want to consider using AM_SUBST_NOTMAKE to prevent automake from adding a line variable = @variable@ to the Makefile.in files (see Automake).

Beyond that, I only turned up a [mailing list post from 2004](https://lists.gnu.org/archive/html/autoconf/2004-02/msg00009.html) that advised against used newlines in `AC_SUBST()` values; however, that was certainly for a much older version of Autoconf.

For the record, my build environment has GNU Autoconf 2.69 and Automake 1.15.

**Comment by lichunqiang** [comment]
```
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.14
```

**Comment by lichunqiang** [comment]
I'm not sure if caused by cross platform.

I used windows and clone the source located on windows system, but i built the source code on the vm(virtualbox) of centos.

Also maybe related with the terminal chartset.

Finally the problem is resolved. Many thanks.
