### ISSUE TITLE
MongoDB\Driver\Manager and PHP pthreads extension

### ISSUE THREAD

**Issue by skoteg** [mongodb/mongo-php-driver#778]
Goog day.

There was a problem using MongoDB\Driver\Manager together with php pthreads extension:
```
class dataProvider extends Threaded
{
	private $db = null;

	public function __construct()
	{
		$this->db = new MongoDB\Driver\Manager(
			'mongodb://user:password@%2Fsrv%2Fmongodb%2Frun%2Fmongodb-27017.sock/database_name',
			['connectTimeoutMS' => 120000]
		);
var_dump($this->db);	// $this->db == NULL !!!
	}
}
```
How can I use MongoDB\Driver\Manager (and MongoDB\Driver\Command, and MongoDB\Driver\Query, and MongoDB\Driver\Cursor) with php pthreads extension?

Sorry for my english and thank you in advance.

**Comment by jmikola** [comment]
I believe your problem lies with usage of the pthreads extension and its Threaded objects. For instance, if you assign the `MongoDB\Driver\Manager` instance to a local `$db` variable, it dumps as you'd expect. I'd suggest reading through all of the documentation on https://github.com/krakjoe/pthreads and the directory of examples. Beyond that, any questions related to pthreads would be better asked on [Stack Overflow](https://stackoverflow.com/), where the extension author has been known to respond from time to time.

While we don't test or guarantee the driver's compatibility with pthreads, I'm not aware of any reason that it would not work as designed provided you aren't sharing its resources (e.g. Manager or Cursor objects) across threads or attempting to use the same object concurrently. I was able to modify [pthread's example for MySQLi](https://github.com/krakjoe/pthreads/blob/master/examples/MySQLi.php) to use MongoDB as follows:

```php
<?php

class Connect extends Worker
{
    private $uri;
    private static $manager; // thread local

    public function __construct(string $uri = null)
    {
        $this->uri = $uri;
    }
    
    public function getConnection(): MongoDB\Driver\Manager {
        if (!self::$manager) {
            self::$manager = new MongoDB\Driver\Manager($this->uri);
        }

        return self::$manager;
    }
}

class Query extends Threaded
{
    private $namespace;
    private $filter;
    private $store;

    public function __construct(string $namespace, array $filter, Threaded $store)
    {
        $this->namespace = $namespace;
        $this->filter = $filter;
        $this->store = $store;
    }

    public function run()
    {
        $manager = $this->worker->getConnection();
        $query = new MongoDB\Driver\Query($this->filter, $this->queryOptions);

        $cursor = $manager->executeQuery($this->namespace, $query);

        foreach ($cursor as $document) {
            $this->store[] = $document;
        }
    }
}

$pool = new Pool(2, "Connect", ['mongodb://127.0.0.1/', [], []]);
$stores = [];

for ($i = 0; $i < 4; ++$i) {
    $store = new Threaded;
    $pool->submit(new Query('test.foo', [], $store));
    $stores[] = $store;
}

$pool->collect();
$pool->shutdown();

var_dump($stores);
```

Before executing this script, I inserted three documents into a `test.foo` collection on the local server:

```
$ mongo
MongoDB shell version v3.6.1
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.6.1
> db.foo.drop()
false
> db.foo.insert({x:1})
WriteResult({ "nInserted" : 1 })
```

Running the PHP script above, we can see the result of four queries printed:

```
$ php threads.php 
array(4) {
  [0]=>
  object(Threaded)#2 (1) {
    [0]=>
    object(stdClass)#9 (2) {
      ["_id"]=>
      object(MongoDB\BSON\ObjectId)#14 (1) {
        ["oid"]=>
        string(24) "5aa847e4dea9e9909a9666a4"
      }
      ["x"]=>
      float(1)
    }
  }
  [1]=>
  object(Threaded)#6 (1) {
    [0]=>
    object(stdClass)#9 (2) {
      ["_id"]=>
      object(MongoDB\BSON\ObjectId)#14 (1) {
        ["oid"]=>
        string(24) "5aa847e4dea9e9909a9666a4"
      }
      ["x"]=>
      float(1)
    }
  }
  [2]=>
  object(Threaded)#10 (1) {
    [0]=>
    object(stdClass)#9 (2) {
      ["_id"]=>
      object(MongoDB\BSON\ObjectId)#14 (1) {
        ["oid"]=>
        string(24) "5aa847e4dea9e9909a9666a4"
      }
      ["x"]=>
      float(1)
    }
  }
  [3]=>
  object(Threaded)#13 (1) {
    [0]=>
    object(stdClass)#9 (2) {
      ["_id"]=>
      object(MongoDB\BSON\ObjectId)#14 (1) {
        ["oid"]=>
        string(24) "5aa847e4dea9e9909a9666a4"
      }
      ["x"]=>
      float(1)
    }
  }
}
```

Watching the `mongod` logs, we can also confirm that the PHP script uses only two connections (i.e. `MongoDB\Driver\Manager` objects), which confirms that pthread's pooling is working as expected.

**Comment by skoteg** [comment]
Jeremy, thank you very much for your reply.
But I have a slightly different problem: you need to organize access from multiple threads to one dataProvider.
This dataProvider should iterate over the cursor of a large collection, and the processing of records must be multi-threaded.
Below is an example of the code that should be executed, but when I run it, I get an error:
```code
Fatal error: Uncaught Error: Call to a member function next() on null in /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php:31
Stack trace:
#0 /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php(67): dataProvider->getNext()
#1 [internal function]: _thread->{closure}(Object(dataProvider))
#2 /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php(69): Threaded->synchronized(Object(Closure), Object(dataProvider))
#3 [internal function]: _thread->run()
#4 {main}
  thrown in /home/resolute/Resolute/instances/www/main/assets/system/os/mt_test_1.php on line 31
```
As far as I understand, the function $provider->synchronized can not work with static variables.

Code that should be executed:
```php
<?php

// one provider for several threads
class dataProvider extends Threaded
{
	private static $db = null;
	private static $cur = null;
	private static $it = null;

	public function __construct()
	{
		self::$db = new MongoDB\Driver\Manager(
			'mongodb://127.0.0.1/',
			['connectTimeoutMS' => 120000]
		);
		$opts = [
			'projection' => [],
			'sort' => [],
			'limit' => false,
			'skip' => 0,
			'modifiers' => ['$maxTimeMS' => 120000],
		];
		$query = new MongoDB\Driver\Query([], $opts);
		self::$cur = self::$db->executeQuery('resolute.documents', $query);
		self::$cur->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
		self::$it = new IteratorIterator(self::$cur);
		self::$it->rewind();
	}
	public function getNext()
	{
		return self::$it->next();
	}
}

class _worker extends Worker
{
	private $provider;

	public function __construct(dataProvider $provider)
	{
		$this->provider = $provider;
	}
	public function getProvider()
	{
		return $this->provider;
	}
	public function run() {}
}

class _thread extends Threaded
{
	private $num;
	public function __construct($num)
	{
		$this->num = $num;
	}

	public function run()
	{
		do {
			$value = null;
			$provider = $this->worker->getProvider();

			// Synchronize getting data from dataProvider
			$provider->synchronized(
				function($provider) use (&$value) {
					$value = $provider->getNext();
				},
				$provider
			);
			if ($value === null) {
				continue;
			}

			// useful action. For example save to file
			// $this->num - is number of thread
			file_put_contents($this->num, $value['code']);
		}
		while ($value !== null);
	}
}

$thrCnt = 4;
$provider = new dataProvider();
$pool = new Pool($thrCnt, '_worker', [$provider]);
for ($i = 0; $i < $thrCnt; $i++) {
	$pool->submit(new _thread($i));
}
$pool->shutdown();

**Comment by jmikola** [comment]
The code example I shared in https://github.com/mongodb/mongo-php-driver/issues/778#issuecomment-372833105 was just a basic modification of an existing pthreads example. I personally have never used the pthreads extension and strongly suggest you take this question to Stack Overflow, where it stands a higher change of being seen by someone with working knowledge of the extension.

Searching the pthreads issue track for similar "Call to a member function" errors turned up https://github.com/krakjoe/pthreads/issues/461#issuecomment-133349490, where the author reiterated that static variables are thread local. In your `dataProvider::getNext()` method, you're expecting `self::$it` to be non-null because it was assigned in the constructor; however, I don't believe the constructor is used to initialize each dataProvider thread. If you contrast that with the approach I used in https://github.com/mongodb/mongo-php-driver/issues/778#issuecomment-372833105 (again, modeled after examples in the pthreads repository), my `getConnection()` accessor method checks if the thread local is initialized and recreates it as necessary.

The PHP.net documentation for the various pthreads classes is is admittedly a bit terse, so I might also suggest trying to find some tutorials that go into more detail if you haven't already. At a glance, https://www.sitepoint.com/parallel-programming-pthreads-php-fundamentals/ seems to go into quite a bit more detail than the official docs.

**Comment by skoteg** [comment]
Jeremy, thank you very much.
Further questions will be asked by Joe.

**Comment by jmikola** [comment]
I'm going to close this issue out. If you run into any issues specific to the MongoDB driver, feel free to open a new issue down the line and we'll be happy to help.

**Comment by skoteg** [comment]
Jeremy, is it planned to implement serialization for MongoDB \ Driver \ Manager and MongoDB \ Driver \ Cursor objects?

**Comment by jmikola** [comment]
> Jeremy, is it planned to implement serialization for MongoDB\Driver\Manager and MongoDB\Driver\Cursor objects?

@skoteg: Unfortunately, both of those object internally reference a libmongoc client object and cannot be serialized. AFAIK, this is also the case with connection objects for other database drivers (e.g. PDO).
