### ISSUE TITLE
Aggregate Query in codeigniter

### ISSUE THREAD

**Issue by RhunaliGosavi** [mongodb/mongo-php-driver#805]
```
db.tablename.aggregate([{"$match" : {"UserID" : "123456"}},
                         {"$group" : {_id : {code:"$code", panno:"$panno"}}},
                         {"$project" : {_id:0, code:"$_id.code", panno:"$_id.panno"}}
            ])
```

PHP query:

```
	 $res = $this->db->fundtrans->aggregate([['$match' => ['UserID' => "123456"]],
                         ['$group' => ['_id' => ['code'=>'$code', 'panno'=>'$panno','Trans_Date'=>'$Trans_Date','UserID'=>'$UserID']]],
                         ['$project' => ['_id'=>0, 'Scode'=>'$_id.code', 'panno'=>'$_id.panno','Trans_Date'=>'$_id.Trans_Date','UserID'=>'$_id.UserID']]]); 				 
						 
						 
	foreach ($res as $person) {
   var_dump($person);
}
```	

Trying to execute above mongo db query in php . but getting below mentioned error.

getting following error:

```
An uncaught Exception was encountered

Type: MongoResultException

Message: 192.168.50.206:27017: The 'cursor' option is required, except for aggregate with the explain argument

Filename: /var/www/truenorthlabs/public_html/application/models/BasicModel.php

Line Number: 675

Backtrace:

File: /var/www/truenorthlabs/public_html/application/models/BasicModel.php
Line: 675
Function: aggregate

File: /var/www/truenorthlabs/public_html/application/controllers/frontend/profile/PortfolioController.php
Line: 1101
Function: getdistinctFundtransDetails

File: /var/www/truenorthlabs/public_html/application/controllers/frontend/profile/PortfolioController.php
Line: 65
Function: fifo_calculation

File: /var/www/truenorthlabs/public_html/index.php
Line: 315
Function: require_once
```

Please Help...

**Comment by jmikola** [comment]
[MongoResultException](http://php.net/manual/en/class.mongoresultexception.php) hints that you're using the legacy [`mongo` extension](http://php.net/manual/en/book.mongo.php), which is no longer supported. This repository tracks issues for the [`mongodb` extension](http://php.net/manual/en/set.mongodb.php).

That said, the [`cursor` option documentation for the `aggregate` command](https://docs.mongodb.com/manual/reference/command/aggregate/#dbcmd.aggregate) may explain why you're seeing this exception:

> Changed in version 3.6: MongoDB 3.6 removes the use of aggregate command without the cursor option unless the command includes the explain option. Unless you include the explain option, you must specify the cursor option.

If you are using the `mongo` extension, this means that you will need to call [`MongoCollection::aggregateCursor()`](http://php.net/manual/en/mongocollection.aggregatecursor.php) instead of [`MongoCollection::aggregate()`](http://php.net/manual/en/mongocollection.aggregate.php). If you are using the `mongodb` extension and the [PHP library](https://github.com/mongodb/mongo-php-library), the [`MongoDB\Collection::aggregate()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-aggregate/) command will automatically use the `cursor` option for you.

If you're using a CodeIgniter library that integrates the MongoDB driver, I would strongly suggest opening an issue on that package as this could be affecting other users as well.

Per [PHP and MongoDB Compatibility](https://docs.mongodb.com/ecosystem/drivers/php/#mongodb-compatibility), the last server version officially supported by the `mongo` extension was MongoDB 3.0. For any newer server versions, you should absolutely be using the newer `mongodb` extension and PHP library.
