### ISSUE TITLE
Connect to Mongo Atlas timeout happened sometimes with PHP library

### ISSUE THREAD

**Issue by abinhho** [mongodb/mongo-php-driver#855]
### Description

Hello pro,

Im using PHP library and PHP `7.0.30`, Mongo Atlas Free Tie and tried to connect, It's successful but looks too slow. I also connected via command line and it's worked as well. When using PHP, 10 times connection got 8 timeout, other times connected, get, insert, update data as normally.

This is my connection code:

```
$client = new \MongoDB\Client("mongodb://<USERNAME>:<PASSWORD>@mycluster0-shard-00-00-bez3z.gcp.mongodb.net:27017,mycluster0-shard-00-01-bez3z.gcp.mongodb.net:27017,mycluster0-shard-00-02-bez3z.gcp.mongodb.net:27017/test?ssl=true&replicaSet=MyCluster0-shard-0&authSource=admin&serverSelectionTryOnce=false&serverSelectionTimeoutMS=15000");
```

This is my timeout info:

```
MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found: `serverSelectionTimeoutMS` expired: [connection timeout calling ismaster on 'mycluster0-shard-00-00-bez3z.gcp.mongodb.net:27017'] [connection timeout calling ismaster on 'mycluster0-shard-00-01-bez3z.gcp.mongodb.net:27017'] [TLS handshake failed: -9806 calling ismaster on 'mycluster0-shard-00-02-bez3z.gcp.mongodb.net:27017'] in src/addons/HbinAws/vendor/mongodb/mongodb/src/Collection.php at line 262
```

Please help !

**Comment by jmikola** [comment]
Assuming you're using macOS (per https://github.com/mongodb/mongo-php-driver/issues/853), I believe you may be hitting [PHPC-1169](https://jira.mongodb.org/browse/PHPC-1169), which should be fixed in 1.5.0 (due to be released within the next two weeks). If you require an immediate solution for your development environment, you can [manually compile the driver](http://php.net/manual/en/mongodb.installation.manual.php) from the master branch of this repository (effectively 1.5.0-dev).

Please read my replies in https://github.com/mongodb/mongo-php-driver/issues/791#issuecomment-383328627 and https://github.com/mongodb/mongo-php-driver/issues/791#issuecomment-383936108. Additionally, you can run the CLI script in my second reply to confirm that you are hitting the same issue.

**Comment by abinhho** [comment]
@jmikola Thanks you ! Command line is works well.

**Comment by jmikola** [comment]
I'll close this. Please follow https://github.com/mongodb/mongo-php-driver/issues/791 for updates, as I'll make a note there when 1.5.0 is released on [PECL](https://pecl.php.net/package/mongodb).

**Comment by jmikola** [comment]
[1.5.0](https://pecl.php.net/package/mongodb/1.5.0) is now available on PECL. We'll have a formal release announcement tomorrow.
