### ISSUE TITLE
Add Manager::getUri(): string

### ISSUE THREAD

**Issue by raffis** [mongodb/mongo-php-driver#908]
### Description

There is no way to retrieve the Uri from a manager instance since it is only applied in the constructor and there is no getter to retrieve it.

Since there are issues like https://github.com/mongodb/mongo-php-driver/issues/828 and child procs need to build a new manager but the manager only has a dependency to a Database (or Manager) and not the URI itself, the parent needs to rebuild the URI manually like:

```
168         $uri = 'mongodb://';
169         if(count($this->db->getManager()->getServers()) === 0) {
170             $this->getCursor();
171         }   
172 
173         foreach($this->db->getManager()->getServers() as $node) {
174             if($uri !== 'mongodb://') {
175                 $uri .= ',';
176             }   
177 
178             $uri .= $node->getHost().':'.$node->getPort();
179         }   
180 
181         return $uri;
```

**Comment by jmikola** [comment]
The URI string is included in the Manager's debug info (e.g. `var_dump()`) in the [`get_debug_info` handler](https://github.com/mongodb/mongo-php-driver/blob/1.5.2/src/MongoDB/Manager.c#L845).

That said, the URI string (i.e. `Manager::__construct()`'s first argument) is not sufficient to recreate a Manager instance in a child process, as its options can be overwritten by the URI options array (second argument). The third argument containing driver options (mostly for SSL) also affects the behavior of a manager instance.

There are likely more robust solutions in userland PHP:

 * Keep the original constructor arguments for the Manager accessible in PHP between the parent and child process. If a Manager is only constructed using the first argument, this may be as easy as defining a URI constant.
 * Create a closure or factory method for yielding a new Manager instance. Assuming it constructs the Manager using the same arguments, all Managers returned by this method will use a common [persisted client](http://php.net/manual/en/mongodb.connection-handling.php) within the same process. Different processes (e.g. children) will use their own persisted libmongoc client.

**Comment by raffis** [comment]
This may be true but if the parent relies on a MongoDB dependency only which is a nicer solution in php userland than depending on a uri and creating the mongodb instance by itself or via factory.

Why not implement all three getOptions, getUri, getDriverOptions ?
But sure I get your point.

**Comment by jmikola** [comment]
> Why not implement all three getOptions, getUri, getDriverOptions?

The constructor's arguments are currently used only within `__construct()` to create the libmongoc client. In order to provide accessor methods for each of these arguments, we'd have to add a reference to each of these zvals to ensure they are kept alive for the lifetime of the Manager instance (memory overhead regardless of whether the accessors would ever be used). We're also conservative about adding to the extension API, especially when solutions exist in PHP userland, due to the development and maintenance burden. If anything, this would be better suited to the library's [`MongoDB\Client`](https://github.com/mongodb/mongo-php-library/blob/master/src/Client.php) class, which already stores the URI string for its own `__debugInfo()` and `__toString()` methods.

**Comment by raffis** [comment]
I did not realize there is a toString method for that in the Client wrapper. Maybe because of my parent instance relies on a Database instance and from that I can only receive the Manager instance and not the Client instance as far as I can see. This is also bad because in that way a class will need a dependency to Client and the name of the database. I personally find it a better dependency to only rely on Database.

**Comment by jmikola** [comment]
> I did not realize there is a toString method for that in the Client wrapper.

For context, we didn't add that `toString()` behavior to be a getter for the URI. Rather, we just wanted some string representation for a Client and the URI seemed the obvious choice. Database and Collection objects can report their name via `toString()`. Not having `toString()` on Client would likely just make debugging more complicated (if folks need to quickly represent a Client in an error log message).

> Maybe because of my parent instance relies on a Database instance and from that I can only receive the Manager instance and not the Client instance as far as I can see.

Indeed, the classes in the library aim to only track their actual dependencies. A Database does not depend on a Client but it does require a Manager to actually execute operations, so we construct it using a Manager. Likewise, Collection's constructor does not take a Database because the only related dependency to a Database is the database name, which we solicit.

> This is also bad because in that way a class will need a dependency to Client and the name of the database. I personally find it a better dependency to only rely on Database.

If you need to access properties of a Manager or Client, OO design principals would advise taking those objects as explicit dependencies instead of indirectly accessing them through the Database object. In the latter case, they are effectively hidden dependencies.

**Comment by raffis** [comment]
I came to the conclusion that it is better to mostly bootstrap a fork (or thread) from scratch. Since I encountered similar problems like #828. Mongodb is not the only problem which can lead to issues using shared connections in forks. Since a fork needs to be bootstrapped from scratch it is also clear how to initialize dependencies (For example using a dic would mean initialising a new dic in each fork and not using the shared dependency tree at all). This will most likely be a more robust setup if you work with forks or threads. Therefore getUri() is not required.
