### ISSUE TITLE
Variable types

### ISSUE THREAD

**Issue by camohub** [mongodb/mongo-php-driver#934]
Hi, I am working with Mongodb + PHP and I dont understand why this driver introduces new types to PHP. Why exists types like BSONUndefined, BSONArray o UTCDatetime? I really dont understand it. Its a lot of work to convert driver types to common data. PHP is not good enough for you? But array is common construct in many other languages. Also the NULL and DateTime. WHY did you do that? 

I would like to have an option to setup the driver so it switches to return normal types. Like BSONUdefined = NULL, BSONArray = array, UTCDatatime = DataTime. 

Tanks for watching.

**Comment by derickr** [comment]
Hi,

The PHP driver only uses a specific type for UTCDateTime. Which we have to do, because PHP's DateTime object (which does contain timezone) doesn't map one-to-one with the databases; UTCDateTime type (which does not contain a timezone).

A BSON array turns into a PHP array (or an object, if you chose to do that through a typemap.) See the documentation at http://php.net/manual/en/mongodb.persistence.deserialization.php 

But a BSON NULL will definitely turn into a PHP NULL as well.

Are you perhaps using a different library on top of the PHP Driver?

cheers,
Derick

**Comment by jmikola** [comment]
You'll need to thoroughly read the [BSON spec](http://bsonspec.org/spec.html) to fully understand why the driver and library (BSONArray is defined by [mongo-php-library](https://github.com/mongodb/mongo-php-library)) use these types, but I'll try to summarize for the three cases you mentioned:

**Undefined**: This type is deprecated, along with the Symbol and DBPointer BSON types, so it should not come up in your application unless you're working with old database records or older versions of other language driver. That said, BSON also has a Null type. If the PHP driver converted BSON's Undefined _and_ Null types to a PHP `null` value, we would lose type fidelity when round-tripping data from MongoDB, to PHP, and back to the database. Therefore, we have classes for each of these three, deprecated types to leave them as-is.

**DateTime**: Prior to PHP 7.1, the [`DateTime` constructor](http://php.net/manual/en/datetime.construct.php) would initialize the sub-second component of a date to zero. The `MongoDB\BSON\UTCDateTime` constructor has always initialized its sub-second component properly.

**Array**: The legacy `ext-mongo` driver used to convert BSON documents and arrays to PHP arrays. That approach had several shortcomings, as described in [Emulating the Legacy Driver](https://docs.mongodb.com/php-library/current/reference/bson/#emulating-the-legacy-driver) within the library manual. As @derickr mentioned, the `ext-mongodb` driver will convert BSON documents and arrays to PHP objects and arrays, respectively; however, the [mongo-php-library](https://github.com/mongodb/mongo-php-library) changes this behavior to return `BSONDocument` and `BSONArray` classes instead (see: [BSON](https://docs.mongodb.com/php-library/current/reference/bson/) in the library manual for more details).

**Comment by camohub** [comment]
Please, if mongodb stores datetime as 64 bit integer and if php transforms it to UTCDateTime how should I handle local timezone? I am missing 2 hours in every DateTime. I seems I need to call 
$utcDateTime->toDateTime()->setTimezone('Europe/Prague') 
This is really not user friendly. I need it in local timezone.

**Comment by jmikola** [comment]
The [Custom Data-Types](https://docs.mongodb.com/php-library/current/tutorial/custom-types/) article in the [library documentation](https://docs.mongodb.com/php-library/) demonstrates one possible way to store a time zone alongside a BSON date and implementing the driver's [UTCDateTimeInterface](http://php.net/manual/en/class.mongodb-bson-utcdatetimeinterface.php). The application still needs to apply to timezone to the DateTime object returned by [`UTCDateTime::toDateTime()`](http://php.net/manual/en/mongodb-bson-utcdatetime.todatetime.php), but the interface makes working with your custom type a bit easier than using a raw UTCDateTime object.

I understand this isn't user-friendly, but the PHP driver doesn't have many options here since the underlying BSON type has no concept of a timezone.

**Comment by camohub** [comment]
One solution is to use php default timezone. It solves most of the usecases.

**Comment by camohub** [comment]
Sorry again, but I need to know how did behave old MongoDate object from older driver to time zones? As new one? It means ->toDateTime() did return UTC DateTime? Cause I have some older repository and there is no `$mongoDate->toDateTime()->setTimeZone()` call. And I don't know if it is mistake or not. So also the old MongoDate should be set up to local via setTimeZone() call? 
Thanks.

**Comment by lindelius** [comment]
Search and you shall find.

http://php.net/manual/en/class.mongodate.php

The old driver did indeed have a `toDateTime()` method, and, just like now, there was no automatic timezone conversion being made.

**Comment by camohub** [comment]
Documentation is not clear and is very brief. So I decide to ask.
Thanks a lot.

**Comment by jmikola** [comment]
> Documentation is not clear and is very brief.

I've updated http://php.net/manual/en/mongodate.todatetime.php to use the same language from http://php.net/manual/en/mongodb-bson-utcdatetime.todatetime.php and clarify that a UTC timezone will be applied to the resulting DateTime object. See: http://svn.php.net/viewvc?view=revision&revision=346700

I'm also going to close this issue, as I believe the original points have been addressed. The comments in [PHPC-760](https://jira.mongodb.org/browse/PHPC-760) explain why we ultimately decided not to introduce a `UTCDateTime::toLocalDateTime()` (or similar) method into the driver.
