### ISSUE TITLE
Server shutdown terminates scripts hanging on event streams

### ISSUE THREAD

**Issue by timwhitlock** [mongodb/mongo-php-driver#971]
### Description

Server shutdown causes any PHP script hanging on an event stream to receive a `SIGTERM` signal and exit, bypassing all normal error handlers.

Using the `pcntl` extension I'm able to keep my script running and reconnect every X seconds. When the signal is ignored I'm able to catch exceptions that are thrown out of the driver. 

e.g. 
```php
pcntl_signal( SIGTERM, SIG_IGN );
while ( true ){
  try {
    // connect and do cool stream stuff
  }
  catch( Exception $e ){
    sleep(5);
  }
}
```
This is all good, except I don't know what other signals could occur. Is `SIGTERM` the only likely signal I need to catch?

Also, it feels like forced script termination isn't good driver behaviour when a server connection disappears. Is this intentional, or unavoidable?

### Environment

```
Mac OS 10.14.4
PHP 7.2.16

libbson bundled version => 1.13.0
libmongoc bundled version => 1.13.0
libmongoc SSL => enabled
libmongoc SSL library => Secure Transport
libmongoc crypto => enabled
libmongoc crypto library => Common Crypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
mongodb.debug => no value => no value
```

Many thanks. Loving event streams so far!

**Comment by jmikola** [comment]
By "event streams", are you referring to [change streams](https://docs.mongodb.com/manual/changeStreams/) (e.g. [`Collection::watch()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-watch/) and processing [change events](https://docs.mongodb.com/manual/reference/change-events/)?

I would not expect a PHP process to terminate under any circumstances due to a dropped server connection.

I tried to reproduce this using a two-node replica set. After launching each `mongod` process running in its own terminal, I connect to the first node, initiate a replica set, and add the second member.

```
$ mongod --version
db version v4.1.10

$ mongod --dbpath /tmp/db1 --replSet rs0 --port 27017
$ mongod --dbpath /tmp/db2 --replSet rs0 --port 27018

$ mongo
> rs.initiate()
> rs.add('localhost:27018');
```

Based on the example you provided, I ran the following PHP CLI script to watch a collection for changes:

```
<?php

require 'vendor/autoload.php';

$client = new MongoDB\Client;
$collection = $client->test->foo;
$collection->drop();

while (true) {
    try {
        $changeStream = $collection->watch();

        printf("[%s] Watching %s for changes\n", date('c'), $collection);

        for ($changeStream->rewind(); true; $changeStream->next()) {
            if ( ! $changeStream->valid()) {
                continue;
            }

            $event = $changeStream->current();

            if ($event['operationType'] === 'invalidate') {
                break;
            }

            $ns = sprintf('%s.%s', $event['ns']['db'], $event['ns']['coll']);

            printf("[%s] Received event\n", date('c'));

            switch ($event['operationType']) {
                case 'insert':
                    printf("Inserted new document in %s\n", $ns);
                    echo json_encode($event['fullDocument']), "\n\n";
                    break;

                default:
                    printf("Unsupported operation type: %s\n\n", $event['operationType']);
            }
        }
    } catch (Exception $e) {
        printf("[%s] Caught %s: %s\n", date('c'), get_class($e), $e->getMessage());
        printf("[%s] Restarting in 5 seconds\n", date('c'));
        sleep(5);
    }
}
```

Running this while inserting some data and restarting the replica set members produced the following output:

```
$ php phpc-gh971.php 
[2019-04-30T09:21:25-04:00] Watching test.foo for changes
[2019-04-30T09:21:39-04:00] Received event
Inserted new document in test.foo
{"_id":{"$oid":"5cc84be395d211b95914bbfc"},"x":1}

[2019-04-30T09:21:41-04:00] Received event
Inserted new document in test.foo
{"_id":{"$oid":"5cc84be595d211b95914bbfd"},"x":2}

[2019-04-30T09:21:44-04:00] Caught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on '127.0.0.1:27017']
[2019-04-30T09:21:44-04:00] Restarting in 5 seconds
[2019-04-30T09:21:49-04:00] Caught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on '127.0.0.1:27017']
[2019-04-30T09:21:49-04:00] Restarting in 5 seconds
[2019-04-30T09:22:04-04:00] Watching test.foo for changes
[2019-04-30T09:22:22-04:00] Received event
Inserted new document in test.foo
{"_id":{"$oid":"5cc84c0eb39da1ca11cec874"},"x":3}

^C
```

After inserting two documents on the primary via a `mongo` shell, I terminated both `mongod` processes with `^C`. This leads to the two server selection exceptions above. I then restarted both `mongod` processes, which come back as secondaries and initiate a new election. That election is responsible for the gap in time between the final "Restarting at 5 seconds" message and "Watching test.foo for changes". The driver spends approximately 15 seconds attempting to [select a server](https://github.com/mongodb/mongo-php-library/blob/1.4.2/src/Collection.php#L1051). After a new primary is elected, I insert another document from a `mongo` shell, which we see as the last event.

I also reproduced the same steps using [`shutdown`](https://docs.mongodb.com/manual/reference/command/shutdown/#dbcmd.shutdown) command (i.e. [`db.shutdownServer()`](https://docs.mongodb.com/manual/reference/method/db.shutdownServer/)). The results were the same as using `^C` to terminate the process.

**Comment by timwhitlock** [comment]
Thanks a lot for looking into this. I think another part of my system was was killing the PHP processes, because isolating the issue with your script I can no longer reproduce the problem. Sorry for wasting your time.

**Comment by jmikola** [comment]
No worries. Happy to help you make better sense of the issue and confirm there wasn't actually an obscure driver bug at play here :smile:

**Comment by timwhitlock** [comment]
Unintended side effect is I also learned a lot about `pcntl_signal`, which I'll use anyway to trigger graceful shudowns that dump the resumeAfter token to disk. Very cool.

Thanks again.

**Comment by gotys** [comment]
> Unintended side effect is I also learned a lot about `pcntl_signal`, which I'll use anyway to trigger graceful shudowns that dump the resumeAfter token to disk. Very cool.
> 
> Thanks again.

Hi guys, found your thread really usefull.
Tim, can you please share an example of using pcntl_signal to terminate the watch() stream ? I've been stuck on this for ages :(

I think it has something to do with PHP's socket_streaming blocking IO .... Have you been able to successfully terminate the $changeStream->next() loop when a SIGTERM arrives ? I need to gracefully shutdown my long-process but I can't seem to figure it out. 

Thanks for all your work !

**Comment by timwhitlock** [comment]
@gotys I just wrap my watch call in a try block and throw an exception from the signal handler.
I don't have a convenient example of the whole thing to post, but the handler binding looks a bit like this:

```php
pcntl_async_signals(true);
pcntl_signal( SIGTERM, function( int $sig ){
    throw new MySigTermException('Caught SIGTERM');
}, false );
```

I use this to catch different signals, such as SIGHUP to force a reconnect. Seems to work, but isn't yet in production so I can't say whether this is a good approach or not. I am also quite far from being an expert in these matters. Good luck.

**Comment by gotys** [comment]
> @gotys I just wrap my watch call in a try block and throw an exception from the signal handler.
> I don't have a convenient example of the whole thing to post, but the handler binding looks a bit like this:
> 
> ```
> pcntl_async_signals(true);
> pcntl_signal( SIGTERM, function( int $sig ){
>     throw new MySigTermException('Caught SIGTERM');
> }, false );
> ```
> 
> I use this to catch different signals, such as SIGHUP to force a reconnect. Seems to work, but isn't yet in production so I can't say whether this is a good approach or not. I am also quite far from being an expert in these matters. Good luck.

Cool, thank you very much. I found my way around using pcntl_signal_dispatch:

```php
pcntl_signal(SIGINT, [$this, 'shutdown']); // Call $this->shutdown() on SIGINT

                for ($changeStream->rewind(); true; $changeStream->next()){
                    pcntl_signal_dispatch();

                    if ( ! $changeStream->valid()) {
                        continue;
                    }

                    $myEvent = $changeStream->current();
........ }
```
