### ISSUE TITLE
Querying with date does not return any results

### ISSUE THREAD

**Issue by JMartelot** [mongodb/mongo-php-driver#989]
Hello,

I'm facing problems using filter with date.

Here, is my configurations:

> mongodb/mongodb : 1.4.2
> php : 7.0
> ext-mongo : 1.5.2

I'm using UTCDateTime with microseconds timestamp.
```php
new UTCDateTime(Carbon::createFromFormat($this->format, $value))
```

See below the generated query, extracted by `MongoDb\Driver\Monitoring\addSubscriber()` (using $date expression):

```javascript
{
  "$and":[
    {
      "DateUpdated":{
        "$gte":{
          "$date":{
            "$numberLong":"1557495946000"
          }
        }
      }
    },
    {
      "DateUpdated":{
        "$lt":{
          "$date":{
            "$numberLong":"1557496246000"
          }
        }
      }
    }
  ]
}
```
This doesn't return any results. 

When I update the query as following : 

```javascript
{
  "$and":[
    {
      "DateUpdated":{
        "$gte":new Date(1557495946000)
      }
    },
    {
      "DateUpdated":{
        "$lt":new Date(1557496246000)
      }
    }
  ]
}
```

I get corrects results, with right datetime range. 
Both queries have been test in Robo3T. 

As describe in the [mongoDb](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#data_date) documentation it seems that the difference is _strict mode_ vs _shell mode_

I can't figure out and can't find any solutions to my problem, although it seems to be related to [this issue](https://github.com/mongodb/mongo-php-driver/issues/187)

Thanks a lot for your help.

**Comment by JMartelot** [comment]
Finally, I found my problem. It was a problem with Robo3T.

**Comment by jmikola** [comment]
For the benefit of anyone else that may come upon this issue in the future: when querying on a BSON UTC date type (0x09 per [the spec](http://bsonspec.org/spec.html)), you should always use the PHP driver's [UTCDateTime](https://www.php.net/manual/en/class.mongodb-bson-utcdatetime.php) class.

Since the `mongo` shell is a JavaScript REPL, the `Date()` type is actually a JavaScript date, which the shell attempts to translate to a BSON date. There is also an `ISODate()` type that is specific to the MongoDB shell (and wraps a `Date()`). The relationship between these types are discussed in the [Data Types in the mongo Shell](https://docs.mongodb.com/manual/core/shell-types/#mongo-shell-date-type) article within the MongoDB manual.

You might think of this as analogous to the relationship between `\DateTime` and `\MongoDB\BSON\UTCDateTime` in the PHP driver; however, the PHP driver currently makes no attempt to translate DateTime to a BSON date type automatically (that must be done through [`UTCDateTime::__construct()`](https://www.php.net/manual/en/mongodb-bson-utcdatetime.construct.php). 

To determine what happens when you inadvertently query with differing types (e.g. BSON date type in the document but an integer in the query), consult the [Comparison/Sort Order](https://docs.mongodb.com/manual/reference/bson-type-comparison-order/) article in the manual. I'll also note that in the PHP driver, any object that _does not_ implement the [MongoDB\BSON\Type](https://www.php.net/manual/en/class.mongodb-bson-type.php) interface will be naively converted to a BSON document in accordance with our [Serialization to BSON](https://www.php.net/manual/en/mongodb.persistence.serialization.php) documentation (e.g. a DateTime will become a BSON document with any of its public properties assigned as fields).
