### ISSUE TITLE
Unclear Client URI options

### ISSUE THREAD

**Issue by cystbear** [mongodb/mongo-php-driver#993]
### How to ensure that my URI options has been applied 

I am using quite simply Client construction flow

```
$client = new Client('mongodb://127.0.0.1/', [
    'serverSelectionTryOnce' => false,
]);
```

but when I do `var_dump($client->getManager());` I got:

```
class MongoDB\Driver\Manager#60 (2) {
  public $uri =>
  string(20) "mongodb://127.0.0.1/"
  public $cluster =>
  array(0) {
  }
}
```

As far as I can see there is no `serverSelectionTryOnce` option at connection URI.
Will be this option used during server selection and/or topology discovering and how I can ensure this?

Optionally, should I add `serverSelectionTryOnce=false` to my connection URI explicitly?

**Comment by jmikola** [comment]
The debug info currently only reports the connection string (i.e. first argument to `Manager::__construct()`). When we parse array options, those are assigned on the internal `mongoc_uri_t` struct after it has already been created from the connection string. As a result, those options are set directly on its internal fields (e.g. BSON documents, strings).

> Will be this option used during server selection and/or topology discovering and how I can ensure this?

The option should certainly be applied, and you should be able to verify based on whether the server selection loop can survive a failover (see [this gist](https://gist.github.com/jmikola/b913a1859fbc79c5eb8cb5dadb62818d) for an example). While you're tweaking this, I might also suggest reducing the `serverSelectionTimeoutMS` value from its 30-second default. If you're using replica sets, this value can be a bit above the expected time for an election (15 seconds might be a good starting point). If you're not using replica sets, then a much smaller value can be used since you're basically just waiting on the driver to connect to a standalone or mongos node.

I've opened [PHPC-1398](https://jira.mongodb.org/browse/PHPC-1398) to track the improvement of reporting additional options that are set via the constructor's second array argument.

**Comment by jmikola** [comment]
Closing. Please follow the linked JIRA issue about for further updates.

**Comment by cystbear** [comment]
Thanks Jeremy!
